/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.kpmg.asrimTables.service.base;

import com.kpmg.asrimTables.model.AsrimHospitals;
import com.kpmg.asrimTables.service.AsrimHospitalsLocalService;
import com.kpmg.asrimTables.service.AsrimHospitalsLocalServiceUtil;
import com.kpmg.asrimTables.service.persistence.AsrimHospitalsPersistence;
import com.kpmg.asrimTables.service.persistence.FooPersistence;

import com.liferay.petra.sql.dsl.query.DSLQuery;
import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;

import java.io.Serializable;

import java.lang.reflect.Field;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the asrim hospitals local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.kpmg.asrimTables.service.impl.AsrimHospitalsLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.kpmg.asrimTables.service.impl.AsrimHospitalsLocalServiceImpl
 * @generated
 */
public abstract class AsrimHospitalsLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AopService, AsrimHospitalsLocalService, IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>AsrimHospitalsLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>AsrimHospitalsLocalServiceUtil</code>.
	 */

	/**
	 * Adds the asrim hospitals to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect AsrimHospitalsLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param asrimHospitals the asrim hospitals
	 * @return the asrim hospitals that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public AsrimHospitals addAsrimHospitals(AsrimHospitals asrimHospitals) {
		asrimHospitals.setNew(true);

		return asrimHospitalsPersistence.update(asrimHospitals);
	}

	/**
	 * Creates a new asrim hospitals with the primary key. Does not add the asrim hospitals to the database.
	 *
	 * @param HOSP_ID the primary key for the new asrim hospitals
	 * @return the new asrim hospitals
	 */
	@Override
	@Transactional(enabled = false)
	public AsrimHospitals createAsrimHospitals(String HOSP_ID) {
		return asrimHospitalsPersistence.create(HOSP_ID);
	}

	/**
	 * Deletes the asrim hospitals with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect AsrimHospitalsLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param HOSP_ID the primary key of the asrim hospitals
	 * @return the asrim hospitals that was removed
	 * @throws PortalException if a asrim hospitals with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public AsrimHospitals deleteAsrimHospitals(String HOSP_ID)
		throws PortalException {

		return asrimHospitalsPersistence.remove(HOSP_ID);
	}

	/**
	 * Deletes the asrim hospitals from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect AsrimHospitalsLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param asrimHospitals the asrim hospitals
	 * @return the asrim hospitals that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public AsrimHospitals deleteAsrimHospitals(AsrimHospitals asrimHospitals) {
		return asrimHospitalsPersistence.remove(asrimHospitals);
	}

	@Override
	public <T> T dslQuery(DSLQuery dslQuery) {
		return asrimHospitalsPersistence.dslQuery(dslQuery);
	}

	@Override
	public int dslQueryCount(DSLQuery dslQuery) {
		Long count = dslQuery(dslQuery);

		return count.intValue();
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			AsrimHospitals.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return asrimHospitalsPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.kpmg.asrimTables.model.impl.AsrimHospitalsModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return asrimHospitalsPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.kpmg.asrimTables.model.impl.AsrimHospitalsModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return asrimHospitalsPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return asrimHospitalsPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return asrimHospitalsPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public AsrimHospitals fetchAsrimHospitals(String HOSP_ID) {
		return asrimHospitalsPersistence.fetchByPrimaryKey(HOSP_ID);
	}

	/**
	 * Returns the asrim hospitals with the primary key.
	 *
	 * @param HOSP_ID the primary key of the asrim hospitals
	 * @return the asrim hospitals
	 * @throws PortalException if a asrim hospitals with the primary key could not be found
	 */
	@Override
	public AsrimHospitals getAsrimHospitals(String HOSP_ID)
		throws PortalException {

		return asrimHospitalsPersistence.findByPrimaryKey(HOSP_ID);
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return asrimHospitalsPersistence.create((String)primaryKeyObj);
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		return asrimHospitalsLocalService.deleteAsrimHospitals(
			(AsrimHospitals)persistedModel);
	}

	@Override
	public BasePersistence<AsrimHospitals> getBasePersistence() {
		return asrimHospitalsPersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return asrimHospitalsPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the asrim hospitalses.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.kpmg.asrimTables.model.impl.AsrimHospitalsModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of asrim hospitalses
	 * @param end the upper bound of the range of asrim hospitalses (not inclusive)
	 * @return the range of asrim hospitalses
	 */
	@Override
	public List<AsrimHospitals> getAsrimHospitalses(int start, int end) {
		return asrimHospitalsPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of asrim hospitalses.
	 *
	 * @return the number of asrim hospitalses
	 */
	@Override
	public int getAsrimHospitalsesCount() {
		return asrimHospitalsPersistence.countAll();
	}

	/**
	 * Updates the asrim hospitals in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect AsrimHospitalsLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param asrimHospitals the asrim hospitals
	 * @return the asrim hospitals that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public AsrimHospitals updateAsrimHospitals(AsrimHospitals asrimHospitals) {
		return asrimHospitalsPersistence.update(asrimHospitals);
	}

	@Deactivate
	protected void deactivate() {
		_setLocalServiceUtilService(null);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			AsrimHospitalsLocalService.class, IdentifiableOSGiService.class,
			PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		asrimHospitalsLocalService = (AsrimHospitalsLocalService)aopProxy;

		_setLocalServiceUtilService(asrimHospitalsLocalService);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return AsrimHospitalsLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return AsrimHospitals.class;
	}

	protected String getModelClassName() {
		return AsrimHospitals.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = asrimHospitalsPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	private void _setLocalServiceUtilService(
		AsrimHospitalsLocalService asrimHospitalsLocalService) {

		try {
			Field field = AsrimHospitalsLocalServiceUtil.class.getDeclaredField(
				"_service");

			field.setAccessible(true);

			field.set(null, asrimHospitalsLocalService);
		}
		catch (ReflectiveOperationException reflectiveOperationException) {
			throw new RuntimeException(reflectiveOperationException);
		}
	}

	protected AsrimHospitalsLocalService asrimHospitalsLocalService;

	@Reference
	protected AsrimHospitalsPersistence asrimHospitalsPersistence;

	@Reference
	protected FooPersistence fooPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

}