/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.kpmg.customtables.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the NewsAndEvents service. Represents a row in the &quot;apgovt_newsandevents&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.kpmg.customtables.model.impl.NewsAndEventsModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.kpmg.customtables.model.impl.NewsAndEventsImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see NewsAndEvents
 * @generated
 */
@ProviderType
public interface NewsAndEventsModel extends BaseModel<NewsAndEvents> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a news and events model instance should use the {@link NewsAndEvents} interface instead.
	 */

	/**
	 * Returns the primary key of this news and events.
	 *
	 * @return the primary key of this news and events
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this news and events.
	 *
	 * @param primaryKey the primary key of this news and events
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this news and events.
	 *
	 * @return the uuid of this news and events
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this news and events.
	 *
	 * @param uuid the uuid of this news and events
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the news ID of this news and events.
	 *
	 * @return the news ID of this news and events
	 */
	public long getNewsId();

	/**
	 * Sets the news ID of this news and events.
	 *
	 * @param newsId the news ID of this news and events
	 */
	public void setNewsId(long newsId);

	/**
	 * Returns the newsdescription of this news and events.
	 *
	 * @return the newsdescription of this news and events
	 */
	@AutoEscape
	public String getNewsdescription();

	/**
	 * Sets the newsdescription of this news and events.
	 *
	 * @param newsdescription the newsdescription of this news and events
	 */
	public void setNewsdescription(String newsdescription);

	/**
	 * Returns the ti_newsdescription of this news and events.
	 *
	 * @return the ti_newsdescription of this news and events
	 */
	@AutoEscape
	public String getTi_newsdescription();

	/**
	 * Sets the ti_newsdescription of this news and events.
	 *
	 * @param ti_newsdescription the ti_newsdescription of this news and events
	 */
	public void setTi_newsdescription(String ti_newsdescription);

	/**
	 * Returns the news date of this news and events.
	 *
	 * @return the news date of this news and events
	 */
	public Date getNewsDate();

	/**
	 * Sets the news date of this news and events.
	 *
	 * @param newsDate the news date of this news and events
	 */
	public void setNewsDate(Date newsDate);

	/**
	 * Returns the file entry ID of this news and events.
	 *
	 * @return the file entry ID of this news and events
	 */
	public long getFileEntryId();

	/**
	 * Sets the file entry ID of this news and events.
	 *
	 * @param fileEntryId the file entry ID of this news and events
	 */
	public void setFileEntryId(long fileEntryId);

	/**
	 * Returns the status of this news and events.
	 *
	 * @return the status of this news and events
	 */
	@AutoEscape
	public String getStatus();

	/**
	 * Sets the status of this news and events.
	 *
	 * @param status the status of this news and events
	 */
	public void setStatus(String status);

	/**
	 * Returns the created date of this news and events.
	 *
	 * @return the created date of this news and events
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this news and events.
	 *
	 * @param createdDate the created date of this news and events
	 */
	public void setCreatedDate(Date createdDate);

	/**
	 * Returns the created by of this news and events.
	 *
	 * @return the created by of this news and events
	 */
	public long getCreatedBy();

	/**
	 * Sets the created by of this news and events.
	 *
	 * @param createdBy the created by of this news and events
	 */
	public void setCreatedBy(long createdBy);

	/**
	 * Returns the modified date of this news and events.
	 *
	 * @return the modified date of this news and events
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this news and events.
	 *
	 * @param modifiedDate the modified date of this news and events
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the modified by of this news and events.
	 *
	 * @return the modified by of this news and events
	 */
	public long getModifiedBy();

	/**
	 * Sets the modified by of this news and events.
	 *
	 * @param modifiedBy the modified by of this news and events
	 */
	public void setModifiedBy(long modifiedBy);

	@Override
	public NewsAndEvents cloneWithOriginalValues();

}