/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.departmentService.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Department service. Represents a row in the &quot;department&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.departmentService.model.impl.DepartmentModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.departmentService.model.impl.DepartmentImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Department
 * @generated
 */
@ProviderType
public interface DepartmentModel extends BaseModel<Department> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a department model instance should use the {@link Department} interface instead.
	 */

	/**
	 * Returns the primary key of this department.
	 *
	 * @return the primary key of this department
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this department.
	 *
	 * @param primaryKey the primary key of this department
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the did of this department.
	 *
	 * @return the did of this department
	 */
	public long getDid();

	/**
	 * Sets the did of this department.
	 *
	 * @param did the did of this department
	 */
	public void setDid(long did);

	/**
	 * Returns the title of this department.
	 *
	 * @return the title of this department
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this department.
	 *
	 * @param title the title of this department
	 */
	public void setTitle(String title);

	/**
	 * Returns the description of this department.
	 *
	 * @return the description of this department
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this department.
	 *
	 * @param description the description of this department
	 */
	public void setDescription(String description);

	/**
	 * Returns the department of this department.
	 *
	 * @return the department of this department
	 */
	public int getDepartment();

	/**
	 * Sets the department of this department.
	 *
	 * @param department the department of this department
	 */
	public void setDepartment(int department);

	@Override
	public Department cloneWithOriginalValues();

}