/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.kpmg.asrimTables.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the AsrimHospitals service. Represents a row in the &quot;asrim_hospitals&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.kpmg.asrimTables.model.impl.AsrimHospitalsModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.kpmg.asrimTables.model.impl.AsrimHospitalsImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AsrimHospitals
 * @generated
 */
@ProviderType
public interface AsrimHospitalsModel extends BaseModel<AsrimHospitals> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a asrim hospitals model instance should use the {@link AsrimHospitals} interface instead.
	 */

	/**
	 * Returns the primary key of this asrim hospitals.
	 *
	 * @return the primary key of this asrim hospitals
	 */
	public String getPrimaryKey();

	/**
	 * Sets the primary key of this asrim hospitals.
	 *
	 * @param primaryKey the primary key of this asrim hospitals
	 */
	public void setPrimaryKey(String primaryKey);

	/**
	 * Returns the hosp_id of this asrim hospitals.
	 *
	 * @return the hosp_id of this asrim hospitals
	 */
	@AutoEscape
	public String getHOSP_ID();

	/**
	 * Sets the hosp_id of this asrim hospitals.
	 *
	 * @param HOSP_ID the hosp_id of this asrim hospitals
	 */
	public void setHOSP_ID(String HOSP_ID);

	/**
	 * Returns the hosp_name of this asrim hospitals.
	 *
	 * @return the hosp_name of this asrim hospitals
	 */
	@AutoEscape
	public String getHOSP_NAME();

	/**
	 * Sets the hosp_name of this asrim hospitals.
	 *
	 * @param HOSP_NAME the hosp_name of this asrim hospitals
	 */
	public void setHOSP_NAME(String HOSP_NAME);

	/**
	 * Returns the hosp_disp_code of this asrim hospitals.
	 *
	 * @return the hosp_disp_code of this asrim hospitals
	 */
	@AutoEscape
	public String getHOSP_DISP_CODE();

	/**
	 * Sets the hosp_disp_code of this asrim hospitals.
	 *
	 * @param HOSP_DISP_CODE the hosp_disp_code of this asrim hospitals
	 */
	public void setHOSP_DISP_CODE(String HOSP_DISP_CODE);

	/**
	 * Returns the hosp_contact_person of this asrim hospitals.
	 *
	 * @return the hosp_contact_person of this asrim hospitals
	 */
	@AutoEscape
	public String getHOSP_CONTACT_PERSON();

	/**
	 * Sets the hosp_contact_person of this asrim hospitals.
	 *
	 * @param HOSP_CONTACT_PERSON the hosp_contact_person of this asrim hospitals
	 */
	public void setHOSP_CONTACT_PERSON(String HOSP_CONTACT_PERSON);

	/**
	 * Returns the hosp_contact_no of this asrim hospitals.
	 *
	 * @return the hosp_contact_no of this asrim hospitals
	 */
	@AutoEscape
	public String getHOSP_CONTACT_NO();

	/**
	 * Sets the hosp_contact_no of this asrim hospitals.
	 *
	 * @param HOSP_CONTACT_NO the hosp_contact_no of this asrim hospitals
	 */
	public void setHOSP_CONTACT_NO(String HOSP_CONTACT_NO);

	/**
	 * Returns the hosp_mithra of this asrim hospitals.
	 *
	 * @return the hosp_mithra of this asrim hospitals
	 */
	@AutoEscape
	public String getHOSP_MITHRA();

	/**
	 * Sets the hosp_mithra of this asrim hospitals.
	 *
	 * @param HOSP_MITHRA the hosp_mithra of this asrim hospitals
	 */
	public void setHOSP_MITHRA(String HOSP_MITHRA);

	/**
	 * Returns the cug_no of this asrim hospitals.
	 *
	 * @return the cug_no of this asrim hospitals
	 */
	@AutoEscape
	public String getCUG_NO();

	/**
	 * Sets the cug_no of this asrim hospitals.
	 *
	 * @param CUG_NO the cug_no of this asrim hospitals
	 */
	public void setCUG_NO(String CUG_NO);

	/**
	 * Returns the hosp_speciality of this asrim hospitals.
	 *
	 * @return the hosp_speciality of this asrim hospitals
	 */
	@AutoEscape
	public String getHOSP_SPECIALITY();

	/**
	 * Sets the hosp_speciality of this asrim hospitals.
	 *
	 * @param HOSP_SPECIALITY the hosp_speciality of this asrim hospitals
	 */
	public void setHOSP_SPECIALITY(String HOSP_SPECIALITY);

	/**
	 * Returns the hosp_city of this asrim hospitals.
	 *
	 * @return the hosp_city of this asrim hospitals
	 */
	@AutoEscape
	public String getHOSP_CITY();

	/**
	 * Sets the hosp_city of this asrim hospitals.
	 *
	 * @param HOSP_CITY the hosp_city of this asrim hospitals
	 */
	public void setHOSP_CITY(String HOSP_CITY);

	/**
	 * Returns the hosp_addr1 of this asrim hospitals.
	 *
	 * @return the hosp_addr1 of this asrim hospitals
	 */
	@AutoEscape
	public String getHOSP_ADDR1();

	/**
	 * Sets the hosp_addr1 of this asrim hospitals.
	 *
	 * @param HOSP_ADDR1 the hosp_addr1 of this asrim hospitals
	 */
	public void setHOSP_ADDR1(String HOSP_ADDR1);

	/**
	 * Returns the hosp_addr2 of this asrim hospitals.
	 *
	 * @return the hosp_addr2 of this asrim hospitals
	 */
	@AutoEscape
	public String getHOSP_ADDR2();

	/**
	 * Sets the hosp_addr2 of this asrim hospitals.
	 *
	 * @param HOSP_ADDR2 the hosp_addr2 of this asrim hospitals
	 */
	public void setHOSP_ADDR2(String HOSP_ADDR2);

	/**
	 * Returns the hosp_addr3 of this asrim hospitals.
	 *
	 * @return the hosp_addr3 of this asrim hospitals
	 */
	@AutoEscape
	public String getHOSP_ADDR3();

	/**
	 * Sets the hosp_addr3 of this asrim hospitals.
	 *
	 * @param HOSP_ADDR3 the hosp_addr3 of this asrim hospitals
	 */
	public void setHOSP_ADDR3(String HOSP_ADDR3);

	/**
	 * Returns the hosp_fax_no of this asrim hospitals.
	 *
	 * @return the hosp_fax_no of this asrim hospitals
	 */
	@AutoEscape
	public String getHOSP_FAX_NO();

	/**
	 * Sets the hosp_fax_no of this asrim hospitals.
	 *
	 * @param HOSP_FAX_NO the hosp_fax_no of this asrim hospitals
	 */
	public void setHOSP_FAX_NO(String HOSP_FAX_NO);

	/**
	 * Returns the hosp_email of this asrim hospitals.
	 *
	 * @return the hosp_email of this asrim hospitals
	 */
	@AutoEscape
	public String getHOSP_EMAIL();

	/**
	 * Sets the hosp_email of this asrim hospitals.
	 *
	 * @param HOSP_EMAIL the hosp_email of this asrim hospitals
	 */
	public void setHOSP_EMAIL(String HOSP_EMAIL);

	/**
	 * Returns the hosp_active_yn of this asrim hospitals.
	 *
	 * @return the hosp_active_yn of this asrim hospitals
	 */
	@AutoEscape
	public String getHOSP_ACTIVE_YN();

	/**
	 * Sets the hosp_active_yn of this asrim hospitals.
	 *
	 * @param HOSP_ACTIVE_YN the hosp_active_yn of this asrim hospitals
	 */
	public void setHOSP_ACTIVE_YN(String HOSP_ACTIVE_YN);

	/**
	 * Returns the crt_dt of this asrim hospitals.
	 *
	 * @return the crt_dt of this asrim hospitals
	 */
	public Date getCRT_DT();

	/**
	 * Sets the crt_dt of this asrim hospitals.
	 *
	 * @param CRT_DT the crt_dt of this asrim hospitals
	 */
	public void setCRT_DT(Date CRT_DT);

	/**
	 * Returns the crt_usr of this asrim hospitals.
	 *
	 * @return the crt_usr of this asrim hospitals
	 */
	@AutoEscape
	public String getCRT_USR();

	/**
	 * Sets the crt_usr of this asrim hospitals.
	 *
	 * @param CRT_USR the crt_usr of this asrim hospitals
	 */
	public void setCRT_USR(String CRT_USR);

	/**
	 * Returns the lst_upd_dt of this asrim hospitals.
	 *
	 * @return the lst_upd_dt of this asrim hospitals
	 */
	public Date getLST_UPD_DT();

	/**
	 * Sets the lst_upd_dt of this asrim hospitals.
	 *
	 * @param LST_UPD_DT the lst_upd_dt of this asrim hospitals
	 */
	public void setLST_UPD_DT(Date LST_UPD_DT);

	/**
	 * Returns the lst_upd_usr of this asrim hospitals.
	 *
	 * @return the lst_upd_usr of this asrim hospitals
	 */
	@AutoEscape
	public String getLST_UPD_USR();

	/**
	 * Sets the lst_upd_usr of this asrim hospitals.
	 *
	 * @param LST_UPD_USR the lst_upd_usr of this asrim hospitals
	 */
	public void setLST_UPD_USR(String LST_UPD_USR);

	/**
	 * Returns the lang_id of this asrim hospitals.
	 *
	 * @return the lang_id of this asrim hospitals
	 */
	@AutoEscape
	public String getLANG_ID();

	/**
	 * Sets the lang_id of this asrim hospitals.
	 *
	 * @param LANG_ID the lang_id of this asrim hospitals
	 */
	public void setLANG_ID(String LANG_ID);

	/**
	 * Returns the hosp_dist_cd of this asrim hospitals.
	 *
	 * @return the hosp_dist_cd of this asrim hospitals
	 */
	@AutoEscape
	public String getHOSP_DIST_CD();

	/**
	 * Sets the hosp_dist_cd of this asrim hospitals.
	 *
	 * @param HOSP_DIST_CD the hosp_dist_cd of this asrim hospitals
	 */
	public void setHOSP_DIST_CD(String HOSP_DIST_CD);

	/**
	 * Returns the hosp_vil_cd of this asrim hospitals.
	 *
	 * @return the hosp_vil_cd of this asrim hospitals
	 */
	@AutoEscape
	public String getHOSP_VIL_CD();

	/**
	 * Sets the hosp_vil_cd of this asrim hospitals.
	 *
	 * @param HOSP_VIL_CD the hosp_vil_cd of this asrim hospitals
	 */
	public void setHOSP_VIL_CD(String HOSP_VIL_CD);

	/**
	 * Returns the account_no of this asrim hospitals.
	 *
	 * @return the account_no of this asrim hospitals
	 */
	@AutoEscape
	public String getACCOUNT_NO();

	/**
	 * Sets the account_no of this asrim hospitals.
	 *
	 * @param ACCOUNT_NO the account_no of this asrim hospitals
	 */
	public void setACCOUNT_NO(String ACCOUNT_NO);

	/**
	 * Returns the bank_id of this asrim hospitals.
	 *
	 * @return the bank_id of this asrim hospitals
	 */
	@AutoEscape
	public String getBANK_ID();

	/**
	 * Sets the bank_id of this asrim hospitals.
	 *
	 * @param BANK_ID the bank_id of this asrim hospitals
	 */
	public void setBANK_ID(String BANK_ID);

	/**
	 * Returns the depo_id of this asrim hospitals.
	 *
	 * @return the depo_id of this asrim hospitals
	 */
	@AutoEscape
	public String getDEPO_ID();

	/**
	 * Sets the depo_id of this asrim hospitals.
	 *
	 * @param DEPO_ID the depo_id of this asrim hospitals
	 */
	public void setDEPO_ID(String DEPO_ID);

	/**
	 * Returns the hosp_account_name of this asrim hospitals.
	 *
	 * @return the hosp_account_name of this asrim hospitals
	 */
	@AutoEscape
	public String getHOSP_ACCOUNT_NAME();

	/**
	 * Sets the hosp_account_name of this asrim hospitals.
	 *
	 * @param HOSP_ACCOUNT_NAME the hosp_account_name of this asrim hospitals
	 */
	public void setHOSP_ACCOUNT_NAME(String HOSP_ACCOUNT_NAME);

	/**
	 * Returns the hosp_type of this asrim hospitals.
	 *
	 * @return the hosp_type of this asrim hospitals
	 */
	@AutoEscape
	public String getHOSP_TYPE();

	/**
	 * Sets the hosp_type of this asrim hospitals.
	 *
	 * @param HOSP_TYPE the hosp_type of this asrim hospitals
	 */
	public void setHOSP_TYPE(String HOSP_TYPE);

	/**
	 * Returns the bill_head_name of this asrim hospitals.
	 *
	 * @return the bill_head_name of this asrim hospitals
	 */
	@AutoEscape
	public String getBILL_HEAD_NAME();

	/**
	 * Sets the bill_head_name of this asrim hospitals.
	 *
	 * @param BILL_HEAD_NAME the bill_head_name of this asrim hospitals
	 */
	public void setBILL_HEAD_NAME(String BILL_HEAD_NAME);

	/**
	 * Returns the bill_head_contact_no of this asrim hospitals.
	 *
	 * @return the bill_head_contact_no of this asrim hospitals
	 */
	@AutoEscape
	public String getBILL_HEAD_CONTACT_NO();

	/**
	 * Sets the bill_head_contact_no of this asrim hospitals.
	 *
	 * @param BILL_HEAD_CONTACT_NO the bill_head_contact_no of this asrim hospitals
	 */
	public void setBILL_HEAD_CONTACT_NO(String BILL_HEAD_CONTACT_NO);

	/**
	 * Returns the bill_head_email of this asrim hospitals.
	 *
	 * @return the bill_head_email of this asrim hospitals
	 */
	@AutoEscape
	public String getBILL_HEAD_EMAIL();

	/**
	 * Sets the bill_head_email of this asrim hospitals.
	 *
	 * @param BILL_HEAD_EMAIL the bill_head_email of this asrim hospitals
	 */
	public void setBILL_HEAD_EMAIL(String BILL_HEAD_EMAIL);

	/**
	 * Returns the ramco_name of this asrim hospitals.
	 *
	 * @return the ramco_name of this asrim hospitals
	 */
	@AutoEscape
	public String getRAMCO_NAME();

	/**
	 * Sets the ramco_name of this asrim hospitals.
	 *
	 * @param RAMCO_NAME the ramco_name of this asrim hospitals
	 */
	public void setRAMCO_NAME(String RAMCO_NAME);

	/**
	 * Returns the ramco_contact_no of this asrim hospitals.
	 *
	 * @return the ramco_contact_no of this asrim hospitals
	 */
	@AutoEscape
	public String getRAMCO_CONTACT_NO();

	/**
	 * Sets the ramco_contact_no of this asrim hospitals.
	 *
	 * @param RAMCO_CONTACT_NO the ramco_contact_no of this asrim hospitals
	 */
	public void setRAMCO_CONTACT_NO(String RAMCO_CONTACT_NO);

	/**
	 * Returns the ramco_email of this asrim hospitals.
	 *
	 * @return the ramco_email of this asrim hospitals
	 */
	@AutoEscape
	public String getRAMCO_EMAIL();

	/**
	 * Sets the ramco_email of this asrim hospitals.
	 *
	 * @param RAMCO_EMAIL the ramco_email of this asrim hospitals
	 */
	public void setRAMCO_EMAIL(String RAMCO_EMAIL);

	/**
	 * Returns the amcco_name of this asrim hospitals.
	 *
	 * @return the amcco_name of this asrim hospitals
	 */
	@AutoEscape
	public String getAMCCO_NAME();

	/**
	 * Sets the amcco_name of this asrim hospitals.
	 *
	 * @param AMCCO_NAME the amcco_name of this asrim hospitals
	 */
	public void setAMCCO_NAME(String AMCCO_NAME);

	/**
	 * Returns the amcco_contact_no of this asrim hospitals.
	 *
	 * @return the amcco_contact_no of this asrim hospitals
	 */
	@AutoEscape
	public String getAMCCO_CONTACT_NO();

	/**
	 * Sets the amcco_contact_no of this asrim hospitals.
	 *
	 * @param AMCCO_CONTACT_NO the amcco_contact_no of this asrim hospitals
	 */
	public void setAMCCO_CONTACT_NO(String AMCCO_CONTACT_NO);

	/**
	 * Returns the amcco_email of this asrim hospitals.
	 *
	 * @return the amcco_email of this asrim hospitals
	 */
	@AutoEscape
	public String getAMCCO_EMAIL();

	/**
	 * Sets the amcco_email of this asrim hospitals.
	 *
	 * @param AMCCO_EMAIL the amcco_email of this asrim hospitals
	 */
	public void setAMCCO_EMAIL(String AMCCO_EMAIL);

	/**
	 * Returns the dist_id of this asrim hospitals.
	 *
	 * @return the dist_id of this asrim hospitals
	 */
	@AutoEscape
	public String getDIST_ID();

	/**
	 * Sets the dist_id of this asrim hospitals.
	 *
	 * @param DIST_ID the dist_id of this asrim hospitals
	 */
	public void setDIST_ID(String DIST_ID);

	/**
	 * Returns the delist_susp_remarks of this asrim hospitals.
	 *
	 * @return the delist_susp_remarks of this asrim hospitals
	 */
	@AutoEscape
	public String getDELIST_SUSP_REMARKS();

	/**
	 * Sets the delist_susp_remarks of this asrim hospitals.
	 *
	 * @param DELIST_SUSP_REMARKS the delist_susp_remarks of this asrim hospitals
	 */
	public void setDELIST_SUSP_REMARKS(String DELIST_SUSP_REMARKS);

	/**
	 * Returns the hosp_empnl_ref_num of this asrim hospitals.
	 *
	 * @return the hosp_empnl_ref_num of this asrim hospitals
	 */
	@AutoEscape
	public String getHOSP_EMPNL_REF_NUM();

	/**
	 * Sets the hosp_empnl_ref_num of this asrim hospitals.
	 *
	 * @param HOSP_EMPNL_REF_NUM the hosp_empnl_ref_num of this asrim hospitals
	 */
	public void setHOSP_EMPNL_REF_NUM(String HOSP_EMPNL_REF_NUM);

	/**
	 * Returns the payments of this asrim hospitals.
	 *
	 * @return the payments of this asrim hospitals
	 */
	@AutoEscape
	public String getPAYMENTS();

	/**
	 * Sets the payments of this asrim hospitals.
	 *
	 * @param PAYMENTS the payments of this asrim hospitals
	 */
	public void setPAYMENTS(String PAYMENTS);

	/**
	 * Returns the hosp_category of this asrim hospitals.
	 *
	 * @return the hosp_category of this asrim hospitals
	 */
	@AutoEscape
	public String getHOSP_CATEGORY();

	/**
	 * Sets the hosp_category of this asrim hospitals.
	 *
	 * @param HOSP_CATEGORY the hosp_category of this asrim hospitals
	 */
	public void setHOSP_CATEGORY(String HOSP_CATEGORY);

	/**
	 * Returns the onbed_patients of this asrim hospitals.
	 *
	 * @return the onbed_patients of this asrim hospitals
	 */
	public int getONBED_PATIENTS();

	/**
	 * Sets the onbed_patients of this asrim hospitals.
	 *
	 * @param ONBED_PATIENTS the onbed_patients of this asrim hospitals
	 */
	public void setONBED_PATIENTS(int ONBED_PATIENTS);

	/**
	 * Returns the govt_hosp_type of this asrim hospitals.
	 *
	 * @return the govt_hosp_type of this asrim hospitals
	 */
	@AutoEscape
	public String getGOVT_HOSP_TYPE();

	/**
	 * Sets the govt_hosp_type of this asrim hospitals.
	 *
	 * @param GOVT_HOSP_TYPE the govt_hosp_type of this asrim hospitals
	 */
	public void setGOVT_HOSP_TYPE(String GOVT_HOSP_TYPE);

	/**
	 * Returns the lst_upd_status_dt of this asrim hospitals.
	 *
	 * @return the lst_upd_status_dt of this asrim hospitals
	 */
	public Date getLST_UPD_STATUS_DT();

	/**
	 * Sets the lst_upd_status_dt of this asrim hospitals.
	 *
	 * @param LST_UPD_STATUS_DT the lst_upd_status_dt of this asrim hospitals
	 */
	public void setLST_UPD_STATUS_DT(Date LST_UPD_STATUS_DT);

	/**
	 * Returns the lst_upd_status_usr of this asrim hospitals.
	 *
	 * @return the lst_upd_status_usr of this asrim hospitals
	 */
	@AutoEscape
	public String getLST_UPD_STATUS_USR();

	/**
	 * Sets the lst_upd_status_usr of this asrim hospitals.
	 *
	 * @param LST_UPD_STATUS_USR the lst_upd_status_usr of this asrim hospitals
	 */
	public void setLST_UPD_STATUS_USR(String LST_UPD_STATUS_USR);

	/**
	 * Returns the hosp_notice of this asrim hospitals.
	 *
	 * @return the hosp_notice of this asrim hospitals
	 */
	@AutoEscape
	public String getHOSP_NOTICE();

	/**
	 * Sets the hosp_notice of this asrim hospitals.
	 *
	 * @param HOSP_NOTICE the hosp_notice of this asrim hospitals
	 */
	public void setHOSP_NOTICE(String HOSP_NOTICE);

	/**
	 * Returns the tds_exemp_status of this asrim hospitals.
	 *
	 * @return the tds_exemp_status of this asrim hospitals
	 */
	@AutoEscape
	public String getTDS_EXEMP_STATUS();

	/**
	 * Sets the tds_exemp_status of this asrim hospitals.
	 *
	 * @param TDS_EXEMP_STATUS the tds_exemp_status of this asrim hospitals
	 */
	public void setTDS_EXEMP_STATUS(String TDS_EXEMP_STATUS);

	/**
	 * Returns the tds_from_dt of this asrim hospitals.
	 *
	 * @return the tds_from_dt of this asrim hospitals
	 */
	public Date getTDS_FROM_DT();

	/**
	 * Sets the tds_from_dt of this asrim hospitals.
	 *
	 * @param TDS_FROM_DT the tds_from_dt of this asrim hospitals
	 */
	public void setTDS_FROM_DT(Date TDS_FROM_DT);

	/**
	 * Returns the tds_to_dt of this asrim hospitals.
	 *
	 * @return the tds_to_dt of this asrim hospitals
	 */
	public Date getTDS_TO_DT();

	/**
	 * Sets the tds_to_dt of this asrim hospitals.
	 *
	 * @param TDS_TO_DT the tds_to_dt of this asrim hospitals
	 */
	public void setTDS_TO_DT(Date TDS_TO_DT);

	/**
	 * Returns the tds_remarks of this asrim hospitals.
	 *
	 * @return the tds_remarks of this asrim hospitals
	 */
	@AutoEscape
	public String getTDS_REMARKS();

	/**
	 * Sets the tds_remarks of this asrim hospitals.
	 *
	 * @param TDS_REMARKS the tds_remarks of this asrim hospitals
	 */
	public void setTDS_REMARKS(String TDS_REMARKS);

	/**
	 * Returns the exemp_ref_no of this asrim hospitals.
	 *
	 * @return the exemp_ref_no of this asrim hospitals
	 */
	@AutoEscape
	public String getEXEMP_REF_NO();

	/**
	 * Sets the exemp_ref_no of this asrim hospitals.
	 *
	 * @param EXEMP_REF_NO the exemp_ref_no of this asrim hospitals
	 */
	public void setEXEMP_REF_NO(String EXEMP_REF_NO);

	/**
	 * Returns the pan_int of this asrim hospitals.
	 *
	 * @return the pan_int of this asrim hospitals
	 */
	@AutoEscape
	public String getPAN_int();

	/**
	 * Sets the pan_int of this asrim hospitals.
	 *
	 * @param PAN_int the pan_int of this asrim hospitals
	 */
	public void setPAN_int(String PAN_int);

	/**
	 * Returns the rev_fund_active of this asrim hospitals.
	 *
	 * @return the rev_fund_active of this asrim hospitals
	 */
	@AutoEscape
	public String getREV_FUND_ACTIVE();

	/**
	 * Sets the rev_fund_active of this asrim hospitals.
	 *
	 * @param REV_FUND_ACTIVE the rev_fund_active of this asrim hospitals
	 */
	public void setREV_FUND_ACTIVE(String REV_FUND_ACTIVE);

	/**
	 * Returns the complaint_type of this asrim hospitals.
	 *
	 * @return the complaint_type of this asrim hospitals
	 */
	@AutoEscape
	public String getCOMPLAINT_TYPE();

	/**
	 * Sets the complaint_type of this asrim hospitals.
	 *
	 * @param COMPLAINT_TYPE the complaint_type of this asrim hospitals
	 */
	public void setCOMPLAINT_TYPE(String COMPLAINT_TYPE);

	/**
	 * Returns the pan_holder_name of this asrim hospitals.
	 *
	 * @return the pan_holder_name of this asrim hospitals
	 */
	@AutoEscape
	public String getPAN_HOLDER_NAME();

	/**
	 * Sets the pan_holder_name of this asrim hospitals.
	 *
	 * @param PAN_HOLDER_NAME the pan_holder_name of this asrim hospitals
	 */
	public void setPAN_HOLDER_NAME(String PAN_HOLDER_NAME);

	/**
	 * Returns the hosp_empnl_date of this asrim hospitals.
	 *
	 * @return the hosp_empnl_date of this asrim hospitals
	 */
	public Date getHOSP_EMPNL_DATE();

	/**
	 * Sets the hosp_empnl_date of this asrim hospitals.
	 *
	 * @param HOSP_EMPNL_DATE the hosp_empnl_date of this asrim hospitals
	 */
	public void setHOSP_EMPNL_DATE(Date HOSP_EMPNL_DATE);

	/**
	 * Returns the hosp_estab_yr of this asrim hospitals.
	 *
	 * @return the hosp_estab_yr of this asrim hospitals
	 */
	@AutoEscape
	public String getHOSP_ESTAB_YR();

	/**
	 * Sets the hosp_estab_yr of this asrim hospitals.
	 *
	 * @param HOSP_ESTAB_YR the hosp_estab_yr of this asrim hospitals
	 */
	public void setHOSP_ESTAB_YR(String HOSP_ESTAB_YR);

	/**
	 * Returns the hosp_amcco_qual of this asrim hospitals.
	 *
	 * @return the hosp_amcco_qual of this asrim hospitals
	 */
	@AutoEscape
	public String getHOSP_AMCCO_QUAL();

	/**
	 * Sets the hosp_amcco_qual of this asrim hospitals.
	 *
	 * @param HOSP_AMCCO_QUAL the hosp_amcco_qual of this asrim hospitals
	 */
	public void setHOSP_AMCCO_QUAL(String HOSP_AMCCO_QUAL);

	/**
	 * Returns the hosp_ramco_qual of this asrim hospitals.
	 *
	 * @return the hosp_ramco_qual of this asrim hospitals
	 */
	@AutoEscape
	public String getHOSP_RAMCO_QUAL();

	/**
	 * Sets the hosp_ramco_qual of this asrim hospitals.
	 *
	 * @param HOSP_RAMCO_QUAL the hosp_ramco_qual of this asrim hospitals
	 */
	public void setHOSP_RAMCO_QUAL(String HOSP_RAMCO_QUAL);

	/**
	 * Returns the hosp_billinghead_qual of this asrim hospitals.
	 *
	 * @return the hosp_billinghead_qual of this asrim hospitals
	 */
	@AutoEscape
	public String getHOSP_BILLINGHEAD_QUAL();

	/**
	 * Sets the hosp_billinghead_qual of this asrim hospitals.
	 *
	 * @param HOSP_BILLINGHEAD_QUAL the hosp_billinghead_qual of this asrim hospitals
	 */
	public void setHOSP_BILLINGHEAD_QUAL(String HOSP_BILLINGHEAD_QUAL);

	/**
	 * Returns the usr_macid of this asrim hospitals.
	 *
	 * @return the usr_macid of this asrim hospitals
	 */
	@AutoEscape
	public String getUSR_MACID();

	/**
	 * Sets the usr_macid of this asrim hospitals.
	 *
	 * @param USR_MACID the usr_macid of this asrim hospitals
	 */
	public void setUSR_MACID(String USR_MACID);

	/**
	 * Returns the hosp_macid of this asrim hospitals.
	 *
	 * @return the hosp_macid of this asrim hospitals
	 */
	@AutoEscape
	public String getHOSP_MACID();

	/**
	 * Sets the hosp_macid of this asrim hospitals.
	 *
	 * @param HOSP_MACID the hosp_macid of this asrim hospitals
	 */
	public void setHOSP_MACID(String HOSP_MACID);

	/**
	 * Returns the biom_required of this asrim hospitals.
	 *
	 * @return the biom_required of this asrim hospitals
	 */
	@AutoEscape
	public String getBIOM_REQUIRED();

	/**
	 * Sets the biom_required of this asrim hospitals.
	 *
	 * @param BIOM_REQUIRED the biom_required of this asrim hospitals
	 */
	public void setBIOM_REQUIRED(String BIOM_REQUIRED);

	/**
	 * Returns the org_type of this asrim hospitals.
	 *
	 * @return the org_type of this asrim hospitals
	 */
	@AutoEscape
	public String getORG_TYPE();

	/**
	 * Sets the org_type of this asrim hospitals.
	 *
	 * @param ORG_TYPE the org_type of this asrim hospitals
	 */
	public void setORG_TYPE(String ORG_TYPE);

	/**
	 * Returns the dlist_claim_confm of this asrim hospitals.
	 *
	 * @return the dlist_claim_confm of this asrim hospitals
	 */
	@AutoEscape
	public String getDLIST_CLAIM_CONFM();

	/**
	 * Sets the dlist_claim_confm of this asrim hospitals.
	 *
	 * @param DLIST_CLAIM_CONFM the dlist_claim_confm of this asrim hospitals
	 */
	public void setDLIST_CLAIM_CONFM(String DLIST_CLAIM_CONFM);

	/**
	 * Returns the dct_fund_active of this asrim hospitals.
	 *
	 * @return the dct_fund_active of this asrim hospitals
	 */
	@AutoEscape
	public String getDCT_FUND_ACTIVE();

	/**
	 * Sets the dct_fund_active of this asrim hospitals.
	 *
	 * @param DCT_FUND_ACTIVE the dct_fund_active of this asrim hospitals
	 */
	public void setDCT_FUND_ACTIVE(String DCT_FUND_ACTIVE);

	/**
	 * Returns the isactive_tg of this asrim hospitals.
	 *
	 * @return the isactive_tg of this asrim hospitals
	 */
	@AutoEscape
	public String getISACTIVE_TG();

	/**
	 * Sets the isactive_tg of this asrim hospitals.
	 *
	 * @param ISACTIVE_TG the isactive_tg of this asrim hospitals
	 */
	public void setISACTIVE_TG(String ISACTIVE_TG);

	/**
	 * Returns the isactive_ap of this asrim hospitals.
	 *
	 * @return the isactive_ap of this asrim hospitals
	 */
	@AutoEscape
	public String getISACTIVE_AP();

	/**
	 * Sets the isactive_ap of this asrim hospitals.
	 *
	 * @param ISACTIVE_AP the isactive_ap of this asrim hospitals
	 */
	public void setISACTIVE_AP(String ISACTIVE_AP);

	/**
	 * Returns the complaint_type_tg of this asrim hospitals.
	 *
	 * @return the complaint_type_tg of this asrim hospitals
	 */
	@AutoEscape
	public String getCOMPLAINT_TYPE_TG();

	/**
	 * Sets the complaint_type_tg of this asrim hospitals.
	 *
	 * @param COMPLAINT_TYPE_TG the complaint_type_tg of this asrim hospitals
	 */
	public void setCOMPLAINT_TYPE_TG(String COMPLAINT_TYPE_TG);

	/**
	 * Returns the block_claims_tg of this asrim hospitals.
	 *
	 * @return the block_claims_tg of this asrim hospitals
	 */
	@AutoEscape
	public String getBLOCK_CLAIMS_TG();

	/**
	 * Sets the block_claims_tg of this asrim hospitals.
	 *
	 * @param BLOCK_CLAIMS_TG the block_claims_tg of this asrim hospitals
	 */
	public void setBLOCK_CLAIMS_TG(String BLOCK_CLAIMS_TG);

	/**
	 * Returns the application_type of this asrim hospitals.
	 *
	 * @return the application_type of this asrim hospitals
	 */
	@AutoEscape
	public String getAPPLICATION_TYPE();

	/**
	 * Sets the application_type of this asrim hospitals.
	 *
	 * @param APPLICATION_TYPE the application_type of this asrim hospitals
	 */
	public void setAPPLICATION_TYPE(String APPLICATION_TYPE);

	/**
	 * Returns the ap_account_no of this asrim hospitals.
	 *
	 * @return the ap_account_no of this asrim hospitals
	 */
	@AutoEscape
	public String getAP_ACCOUNT_NO();

	/**
	 * Sets the ap_account_no of this asrim hospitals.
	 *
	 * @param AP_ACCOUNT_NO the ap_account_no of this asrim hospitals
	 */
	public void setAP_ACCOUNT_NO(String AP_ACCOUNT_NO);

	/**
	 * Returns the ap_bank_id of this asrim hospitals.
	 *
	 * @return the ap_bank_id of this asrim hospitals
	 */
	@AutoEscape
	public String getAP_BANK_ID();

	/**
	 * Sets the ap_bank_id of this asrim hospitals.
	 *
	 * @param AP_BANK_ID the ap_bank_id of this asrim hospitals
	 */
	public void setAP_BANK_ID(String AP_BANK_ID);

	/**
	 * Returns the ap_hosp_account_name of this asrim hospitals.
	 *
	 * @return the ap_hosp_account_name of this asrim hospitals
	 */
	@AutoEscape
	public String getAP_HOSP_ACCOUNT_NAME();

	/**
	 * Sets the ap_hosp_account_name of this asrim hospitals.
	 *
	 * @param AP_HOSP_ACCOUNT_NAME the ap_hosp_account_name of this asrim hospitals
	 */
	public void setAP_HOSP_ACCOUNT_NAME(String AP_HOSP_ACCOUNT_NAME);

	/**
	 * Returns the biom_required_ap of this asrim hospitals.
	 *
	 * @return the biom_required_ap of this asrim hospitals
	 */
	@AutoEscape
	public String getBIOM_REQUIRED_AP();

	/**
	 * Sets the biom_required_ap of this asrim hospitals.
	 *
	 * @param BIOM_REQUIRED_AP the biom_required_ap of this asrim hospitals
	 */
	public void setBIOM_REQUIRED_AP(String BIOM_REQUIRED_AP);

	/**
	 * Returns the medco_login_created of this asrim hospitals.
	 *
	 * @return the medco_login_created of this asrim hospitals
	 */
	@AutoEscape
	public String getMEDCO_LOGIN_CREATED();

	/**
	 * Sets the medco_login_created of this asrim hospitals.
	 *
	 * @param MEDCO_LOGIN_CREATED the medco_login_created of this asrim hospitals
	 */
	public void setMEDCO_LOGIN_CREATED(String MEDCO_LOGIN_CREATED);

	/**
	 * Returns the dist_id_old of this asrim hospitals.
	 *
	 * @return the dist_id_old of this asrim hospitals
	 */
	@AutoEscape
	public String getDIST_ID_OLD();

	/**
	 * Sets the dist_id_old of this asrim hospitals.
	 *
	 * @param DIST_ID_OLD the dist_id_old of this asrim hospitals
	 */
	public void setDIST_ID_OLD(String DIST_ID_OLD);

	/**
	 * Returns the ap_patient_care_bankid of this asrim hospitals.
	 *
	 * @return the ap_patient_care_bankid of this asrim hospitals
	 */
	@AutoEscape
	public String getAP_PATIENT_CARE_BANKID();

	/**
	 * Sets the ap_patient_care_bankid of this asrim hospitals.
	 *
	 * @param AP_PATIENT_CARE_BANKID the ap_patient_care_bankid of this asrim hospitals
	 */
	public void setAP_PATIENT_CARE_BANKID(String AP_PATIENT_CARE_BANKID);

	/**
	 * Returns the ap_incentive_care_bank_id of this asrim hospitals.
	 *
	 * @return the ap_incentive_care_bank_id of this asrim hospitals
	 */
	@AutoEscape
	public String getAP_INCENTIVE_CARE_BANK_ID();

	/**
	 * Sets the ap_incentive_care_bank_id of this asrim hospitals.
	 *
	 * @param AP_INCENTIVE_CARE_BANK_ID the ap_incentive_care_bank_id of this asrim hospitals
	 */
	public void setAP_INCENTIVE_CARE_BANK_ID(String AP_INCENTIVE_CARE_BANK_ID);

	/**
	 * Returns the patient_care_account_no of this asrim hospitals.
	 *
	 * @return the patient_care_account_no of this asrim hospitals
	 */
	@AutoEscape
	public String getPATIENT_CARE_ACCOUNT_NO();

	/**
	 * Sets the patient_care_account_no of this asrim hospitals.
	 *
	 * @param PATIENT_CARE_ACCOUNT_NO the patient_care_account_no of this asrim hospitals
	 */
	public void setPATIENT_CARE_ACCOUNT_NO(String PATIENT_CARE_ACCOUNT_NO);

	/**
	 * Returns the incentive_care_account_no of this asrim hospitals.
	 *
	 * @return the incentive_care_account_no of this asrim hospitals
	 */
	@AutoEscape
	public String getINCENTIVE_CARE_ACCOUNT_NO();

	/**
	 * Sets the incentive_care_account_no of this asrim hospitals.
	 *
	 * @param INCENTIVE_CARE_ACCOUNT_NO the incentive_care_account_no of this asrim hospitals
	 */
	public void setINCENTIVE_CARE_ACCOUNT_NO(String INCENTIVE_CARE_ACCOUNT_NO);

	/**
	 * Returns the ap_patcare_hosp_ac_name of this asrim hospitals.
	 *
	 * @return the ap_patcare_hosp_ac_name of this asrim hospitals
	 */
	@AutoEscape
	public String getAP_PATCARE_HOSP_AC_NAME();

	/**
	 * Sets the ap_patcare_hosp_ac_name of this asrim hospitals.
	 *
	 * @param AP_PATCARE_HOSP_AC_NAME the ap_patcare_hosp_ac_name of this asrim hospitals
	 */
	public void setAP_PATCARE_HOSP_AC_NAME(String AP_PATCARE_HOSP_AC_NAME);

	/**
	 * Returns the ap_inccare_hosp_ac_name of this asrim hospitals.
	 *
	 * @return the ap_inccare_hosp_ac_name of this asrim hospitals
	 */
	@AutoEscape
	public String getAP_INCCARE_HOSP_AC_NAME();

	/**
	 * Sets the ap_inccare_hosp_ac_name of this asrim hospitals.
	 *
	 * @param AP_INCCARE_HOSP_AC_NAME the ap_inccare_hosp_ac_name of this asrim hospitals
	 */
	public void setAP_INCCARE_HOSP_AC_NAME(String AP_INCCARE_HOSP_AC_NAME);

	/**
	 * Returns the err_msgs of this asrim hospitals.
	 *
	 * @return the err_msgs of this asrim hospitals
	 */
	@AutoEscape
	public String getERR_MSGS();

	/**
	 * Sets the err_msgs of this asrim hospitals.
	 *
	 * @param ERR_MSGS the err_msgs of this asrim hospitals
	 */
	public void setERR_MSGS(String ERR_MSGS);

	/**
	 * Returns the nhpm_upd of this asrim hospitals.
	 *
	 * @return the nhpm_upd of this asrim hospitals
	 */
	@AutoEscape
	public String getNHPM_UPD();

	/**
	 * Sets the nhpm_upd of this asrim hospitals.
	 *
	 * @param NHPM_UPD the nhpm_upd of this asrim hospitals
	 */
	public void setNHPM_UPD(String NHPM_UPD);

	/**
	 * Returns the ehs_reference_numbe of this asrim hospitals.
	 *
	 * @return the ehs_reference_numbe of this asrim hospitals
	 */
	@AutoEscape
	public String getEHS_REFERENCE_NUMBE();

	/**
	 * Sets the ehs_reference_numbe of this asrim hospitals.
	 *
	 * @param EHS_REFERENCE_NUMBE the ehs_reference_numbe of this asrim hospitals
	 */
	public void setEHS_REFERENCE_NUMBE(String EHS_REFERENCE_NUMBE);

	/**
	 * Returns the nhpm_upd_add of this asrim hospitals.
	 *
	 * @return the nhpm_upd_add of this asrim hospitals
	 */
	@AutoEscape
	public String getNHPM_UPD_ADD();

	/**
	 * Sets the nhpm_upd_add of this asrim hospitals.
	 *
	 * @param NHPM_UPD_ADD the nhpm_upd_add of this asrim hospitals
	 */
	public void setNHPM_UPD_ADD(String NHPM_UPD_ADD);

	/**
	 * Returns the err_msgs_add of this asrim hospitals.
	 *
	 * @return the err_msgs_add of this asrim hospitals
	 */
	@AutoEscape
	public String getERR_MSGS_ADD();

	/**
	 * Sets the err_msgs_add of this asrim hospitals.
	 *
	 * @param ERR_MSGS_ADD the err_msgs_add of this asrim hospitals
	 */
	public void setERR_MSGS_ADD(String ERR_MSGS_ADD);

	/**
	 * Returns the nhpm_upm_hosp_attach of this asrim hospitals.
	 *
	 * @return the nhpm_upm_hosp_attach of this asrim hospitals
	 */
	@AutoEscape
	public String getNHPM_UPM_HOSP_ATTACH();

	/**
	 * Sets the nhpm_upm_hosp_attach of this asrim hospitals.
	 *
	 * @param NHPM_UPM_HOSP_ATTACH the nhpm_upm_hosp_attach of this asrim hospitals
	 */
	public void setNHPM_UPM_HOSP_ATTACH(String NHPM_UPM_HOSP_ATTACH);

	/**
	 * Returns the hosp_name_tel of this asrim hospitals.
	 *
	 * @return the hosp_name_tel of this asrim hospitals
	 */
	@AutoEscape
	public String getHOSP_NAME_TEL();

	/**
	 * Sets the hosp_name_tel of this asrim hospitals.
	 *
	 * @param HOSP_NAME_TEL the hosp_name_tel of this asrim hospitals
	 */
	public void setHOSP_NAME_TEL(String HOSP_NAME_TEL);

	/**
	 * Returns the infra_upd of this asrim hospitals.
	 *
	 * @return the infra_upd of this asrim hospitals
	 */
	@AutoEscape
	public String getINFRA_UPD();

	/**
	 * Sets the infra_upd of this asrim hospitals.
	 *
	 * @param INFRA_UPD the infra_upd of this asrim hospitals
	 */
	public void setINFRA_UPD(String INFRA_UPD);

	/**
	 * Returns the err_msgs_infra of this asrim hospitals.
	 *
	 * @return the err_msgs_infra of this asrim hospitals
	 */
	@AutoEscape
	public String getERR_MSGS_INFRA();

	/**
	 * Sets the err_msgs_infra of this asrim hospitals.
	 *
	 * @param ERR_MSGS_INFRA the err_msgs_infra of this asrim hospitals
	 */
	public void setERR_MSGS_INFRA(String ERR_MSGS_INFRA);

	/**
	 * Returns the covid_nwh_status of this asrim hospitals.
	 *
	 * @return the covid_nwh_status of this asrim hospitals
	 */
	@AutoEscape
	public String getCOVID_NWH_STATUS();

	/**
	 * Sets the covid_nwh_status of this asrim hospitals.
	 *
	 * @param COVID_NWH_STATUS the covid_nwh_status of this asrim hospitals
	 */
	public void setCOVID_NWH_STATUS(String COVID_NWH_STATUS);

	/**
	 * Returns the temporary_hospital of this asrim hospitals.
	 *
	 * @return the temporary_hospital of this asrim hospitals
	 */
	@AutoEscape
	public String getTEMPORARY_HOSPITAL();

	/**
	 * Sets the temporary_hospital of this asrim hospitals.
	 *
	 * @param TEMPORARY_HOSPITAL the temporary_hospital of this asrim hospitals
	 */
	public void setTEMPORARY_HOSPITAL(String TEMPORARY_HOSPITAL);

	/**
	 * Returns the nhpm_hosp_id of this asrim hospitals.
	 *
	 * @return the nhpm_hosp_id of this asrim hospitals
	 */
	@AutoEscape
	public String getNHPM_HOSP_ID();

	/**
	 * Sets the nhpm_hosp_id of this asrim hospitals.
	 *
	 * @param NHPM_HOSP_ID the nhpm_hosp_id of this asrim hospitals
	 */
	public void setNHPM_HOSP_ID(String NHPM_HOSP_ID);

	/**
	 * Returns the nhpm_upd_dt of this asrim hospitals.
	 *
	 * @return the nhpm_upd_dt of this asrim hospitals
	 */
	public Date getNHPM_UPD_DT();

	/**
	 * Sets the nhpm_upd_dt of this asrim hospitals.
	 *
	 * @param NHPM_UPD_DT the nhpm_upd_dt of this asrim hospitals
	 */
	public void setNHPM_UPD_DT(Date NHPM_UPD_DT);

	/**
	 * Returns the nhpm_upd_add_dt of this asrim hospitals.
	 *
	 * @return the nhpm_upd_add_dt of this asrim hospitals
	 */
	public Date getNHPM_UPD_ADD_DT();

	/**
	 * Sets the nhpm_upd_add_dt of this asrim hospitals.
	 *
	 * @param NHPM_UPD_ADD_DT the nhpm_upd_add_dt of this asrim hospitals
	 */
	public void setNHPM_UPD_ADD_DT(Date NHPM_UPD_ADD_DT);

	/**
	 * Returns the nhpm_upd_hosp_attach_dt of this asrim hospitals.
	 *
	 * @return the nhpm_upd_hosp_attach_dt of this asrim hospitals
	 */
	public Date getNHPM_UPD_HOSP_ATTACH_DT();

	/**
	 * Sets the nhpm_upd_hosp_attach_dt of this asrim hospitals.
	 *
	 * @param NHPM_UPD_HOSP_ATTACH_DT the nhpm_upd_hosp_attach_dt of this asrim hospitals
	 */
	public void setNHPM_UPD_HOSP_ATTACH_DT(Date NHPM_UPD_HOSP_ATTACH_DT);

	/**
	 * Returns the infra_upd_dt of this asrim hospitals.
	 *
	 * @return the infra_upd_dt of this asrim hospitals
	 */
	public Date getINFRA_UPD_DT();

	/**
	 * Sets the infra_upd_dt of this asrim hospitals.
	 *
	 * @param INFRA_UPD_DT the infra_upd_dt of this asrim hospitals
	 */
	public void setINFRA_UPD_DT(Date INFRA_UPD_DT);

	/**
	 * Returns the response_cnt of this asrim hospitals.
	 *
	 * @return the response_cnt of this asrim hospitals
	 */
	@AutoEscape
	public String getRESPONSE_CNT();

	/**
	 * Sets the response_cnt of this asrim hospitals.
	 *
	 * @param RESPONSE_CNT the response_cnt of this asrim hospitals
	 */
	public void setRESPONSE_CNT(String RESPONSE_CNT);

	/**
	 * Returns the err_msgs_hosp_attach of this asrim hospitals.
	 *
	 * @return the err_msgs_hosp_attach of this asrim hospitals
	 */
	@AutoEscape
	public String getERR_MSGS_HOSP_ATTACH();

	/**
	 * Sets the err_msgs_hosp_attach of this asrim hospitals.
	 *
	 * @param ERR_MSGS_HOSP_ATTACH the err_msgs_hosp_attach of this asrim hospitals
	 */
	public void setERR_MSGS_HOSP_ATTACH(String ERR_MSGS_HOSP_ATTACH);

	/**
	 * Returns the pan_number of this asrim hospitals.
	 *
	 * @return the pan_number of this asrim hospitals
	 */
	@AutoEscape
	public String getPAN_NUMBER();

	/**
	 * Sets the pan_number of this asrim hospitals.
	 *
	 * @param PAN_NUMBER the pan_number of this asrim hospitals
	 */
	public void setPAN_NUMBER(String PAN_NUMBER);

	@Override
	public AsrimHospitals cloneWithOriginalValues();

}