/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.kpmg.asrimTables.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the AsrimLocations service. Represents a row in the &quot;asrim_locations&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.kpmg.asrimTables.model.impl.AsrimLocationsModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.kpmg.asrimTables.model.impl.AsrimLocationsImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AsrimLocations
 * @generated
 */
@ProviderType
public interface AsrimLocationsModel extends BaseModel<AsrimLocations> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a asrim locations model instance should use the {@link AsrimLocations} interface instead.
	 */

	/**
	 * Returns the primary key of this asrim locations.
	 *
	 * @return the primary key of this asrim locations
	 */
	public String getPrimaryKey();

	/**
	 * Sets the primary key of this asrim locations.
	 *
	 * @param primaryKey the primary key of this asrim locations
	 */
	public void setPrimaryKey(String primaryKey);

	/**
	 * Returns the loc_id of this asrim locations.
	 *
	 * @return the loc_id of this asrim locations
	 */
	@AutoEscape
	public String getLOC_ID();

	/**
	 * Sets the loc_id of this asrim locations.
	 *
	 * @param LOC_ID the loc_id of this asrim locations
	 */
	public void setLOC_ID(String LOC_ID);

	/**
	 * Returns the loc_name of this asrim locations.
	 *
	 * @return the loc_name of this asrim locations
	 */
	@AutoEscape
	public String getLOC_NAME();

	/**
	 * Sets the loc_name of this asrim locations.
	 *
	 * @param LOC_NAME the loc_name of this asrim locations
	 */
	public void setLOC_NAME(String LOC_NAME);

	/**
	 * Returns the loc_parnt_id of this asrim locations.
	 *
	 * @return the loc_parnt_id of this asrim locations
	 */
	@AutoEscape
	public String getLOC_PARNT_ID();

	/**
	 * Sets the loc_parnt_id of this asrim locations.
	 *
	 * @param LOC_PARNT_ID the loc_parnt_id of this asrim locations
	 */
	public void setLOC_PARNT_ID(String LOC_PARNT_ID);

	/**
	 * Returns the loc_order of this asrim locations.
	 *
	 * @return the loc_order of this asrim locations
	 */
	@AutoEscape
	public String getLOC_ORDER();

	/**
	 * Sets the loc_order of this asrim locations.
	 *
	 * @param LOC_ORDER the loc_order of this asrim locations
	 */
	public void setLOC_ORDER(String LOC_ORDER);

	/**
	 * Returns the loc_desc of this asrim locations.
	 *
	 * @return the loc_desc of this asrim locations
	 */
	@AutoEscape
	public String getLOC_DESC();

	/**
	 * Sets the loc_desc of this asrim locations.
	 *
	 * @param LOC_DESC the loc_desc of this asrim locations
	 */
	public void setLOC_DESC(String LOC_DESC);

	/**
	 * Returns the loc_val of this asrim locations.
	 *
	 * @return the loc_val of this asrim locations
	 */
	@AutoEscape
	public String getLOC_VAL();

	/**
	 * Sets the loc_val of this asrim locations.
	 *
	 * @param LOC_VAL the loc_val of this asrim locations
	 */
	public void setLOC_VAL(String LOC_VAL);

	/**
	 * Returns the lang_id of this asrim locations.
	 *
	 * @return the lang_id of this asrim locations
	 */
	@AutoEscape
	public String getLANG_ID();

	/**
	 * Sets the lang_id of this asrim locations.
	 *
	 * @param LANG_ID the lang_id of this asrim locations
	 */
	public void setLANG_ID(String LANG_ID);

	/**
	 * Returns the crt_usr of this asrim locations.
	 *
	 * @return the crt_usr of this asrim locations
	 */
	@AutoEscape
	public String getCRT_USR();

	/**
	 * Sets the crt_usr of this asrim locations.
	 *
	 * @param CRT_USR the crt_usr of this asrim locations
	 */
	public void setCRT_USR(String CRT_USR);

	/**
	 * Returns the crt_dt of this asrim locations.
	 *
	 * @return the crt_dt of this asrim locations
	 */
	public Date getCRT_DT();

	/**
	 * Sets the crt_dt of this asrim locations.
	 *
	 * @param CRT_DT the crt_dt of this asrim locations
	 */
	public void setCRT_DT(Date CRT_DT);

	/**
	 * Returns the lst_upd_usr of this asrim locations.
	 *
	 * @return the lst_upd_usr of this asrim locations
	 */
	@AutoEscape
	public String getLST_UPD_USR();

	/**
	 * Sets the lst_upd_usr of this asrim locations.
	 *
	 * @param LST_UPD_USR the lst_upd_usr of this asrim locations
	 */
	public void setLST_UPD_USR(String LST_UPD_USR);

	/**
	 * Returns the lst_upd_dt of this asrim locations.
	 *
	 * @return the lst_upd_dt of this asrim locations
	 */
	public Date getLST_UPD_DT();

	/**
	 * Sets the lst_upd_dt of this asrim locations.
	 *
	 * @param LST_UPD_DT the lst_upd_dt of this asrim locations
	 */
	public void setLST_UPD_DT(Date LST_UPD_DT);

	/**
	 * Returns the loc_hdr_id of this asrim locations.
	 *
	 * @return the loc_hdr_id of this asrim locations
	 */
	@AutoEscape
	public String getLOC_HDR_ID();

	/**
	 * Sets the loc_hdr_id of this asrim locations.
	 *
	 * @param LOC_HDR_ID the loc_hdr_id of this asrim locations
	 */
	public void setLOC_HDR_ID(String LOC_HDR_ID);

	/**
	 * Returns the active_yn of this asrim locations.
	 *
	 * @return the active_yn of this asrim locations
	 */
	@AutoEscape
	public String getACTIVE_YN();

	/**
	 * Sets the active_yn of this asrim locations.
	 *
	 * @param ACTIVE_YN the active_yn of this asrim locations
	 */
	public void setACTIVE_YN(String ACTIVE_YN);

	/**
	 * Returns the itda of this asrim locations.
	 *
	 * @return the itda of this asrim locations
	 */
	@AutoEscape
	public String getITDA();

	/**
	 * Sets the itda of this asrim locations.
	 *
	 * @param ITDA the itda of this asrim locations
	 */
	public void setITDA(String ITDA);

	/**
	 * Returns the itda_area of this asrim locations.
	 *
	 * @return the itda_area of this asrim locations
	 */
	@AutoEscape
	public String getITDA_AREA();

	/**
	 * Sets the itda_area of this asrim locations.
	 *
	 * @param ITDA_AREA the itda_area of this asrim locations
	 */
	public void setITDA_AREA(String ITDA_AREA);

	/**
	 * Returns the urban_rural of this asrim locations.
	 *
	 * @return the urban_rural of this asrim locations
	 */
	@AutoEscape
	public String getURBAN_RURAL();

	/**
	 * Sets the urban_rural of this asrim locations.
	 *
	 * @param URBAN_RURAL the urban_rural of this asrim locations
	 */
	public void setURBAN_RURAL(String URBAN_RURAL);

	/**
	 * Returns the pincode of this asrim locations.
	 *
	 * @return the pincode of this asrim locations
	 */
	@AutoEscape
	public String getPINCODE();

	/**
	 * Sets the pincode of this asrim locations.
	 *
	 * @param PINCODE the pincode of this asrim locations
	 */
	public void setPINCODE(String PINCODE);

	/**
	 * Returns the is_crda_location of this asrim locations.
	 *
	 * @return the is_crda_location of this asrim locations
	 */
	@AutoEscape
	public String getIS_CRDA_LOCATION();

	/**
	 * Sets the is_crda_location of this asrim locations.
	 *
	 * @param IS_CRDA_LOCATION the is_crda_location of this asrim locations
	 */
	public void setIS_CRDA_LOCATION(String IS_CRDA_LOCATION);

	/**
	 * Returns the ehs_location_id of this asrim locations.
	 *
	 * @return the ehs_location_id of this asrim locations
	 */
	@AutoEscape
	public String getEHS_LOCATION_ID();

	/**
	 * Sets the ehs_location_id of this asrim locations.
	 *
	 * @param EHS_LOCATION_ID the ehs_location_id of this asrim locations
	 */
	public void setEHS_LOCATION_ID(String EHS_LOCATION_ID);

	/**
	 * Returns the rural_urban of this asrim locations.
	 *
	 * @return the rural_urban of this asrim locations
	 */
	@AutoEscape
	public String getRURAL_URBAN();

	/**
	 * Sets the rural_urban of this asrim locations.
	 *
	 * @param RURAL_URBAN the rural_urban of this asrim locations
	 */
	public void setRURAL_URBAN(String RURAL_URBAN);

	/**
	 * Returns the loc_desc_tel of this asrim locations.
	 *
	 * @return the loc_desc_tel of this asrim locations
	 */
	@AutoEscape
	public String getLOC_DESC_TEL();

	/**
	 * Sets the loc_desc_tel of this asrim locations.
	 *
	 * @param LOC_DESC_TEL the loc_desc_tel of this asrim locations
	 */
	public void setLOC_DESC_TEL(String LOC_DESC_TEL);

	/**
	 * Returns the loc_state_val of this asrim locations.
	 *
	 * @return the loc_state_val of this asrim locations
	 */
	@AutoEscape
	public String getLOC_STATE_VAL();

	/**
	 * Sets the loc_state_val of this asrim locations.
	 *
	 * @param LOC_STATE_VAL the loc_state_val of this asrim locations
	 */
	public void setLOC_STATE_VAL(String LOC_STATE_VAL);

	@Override
	public AsrimLocations cloneWithOriginalValues();

}