<#assign
home="Home"
about="About Us"
faq = "FAQ"
covid = "COVID - 19"
schemes = "Schemes"
trust = "DR. YSR AAROGYASRI HEALTH CARE TRUST"
ap_state_govt = "ANDHRA PRADESH STATE GOVERNMENT"
sign_in = "Sign-in"
contact = "Contact"
ehs_short = "EHS"
asri = "Dr.YSR Aarogyasri"
ehs = "Employee Health Scheme"
wjhs_short = "WJHS"
wjhs = "Working Journalist Health Scheme"
ar = "Aarogya Raksha"
copyright = "Site maintained by KPMG Advisory Services Pvt. Ltd. The contents are owned by Govt.of AP,India."

door_number = "Door No"
building = "MGM Capital Building "
chinakakani = "Chinnakakani"
mangalagiri = "Mangalagiri"
guntur = "Guntur Dist"
pin_code = "Pin"
ap = "Andhra Pradesh "
india = "India "
call = "Call 104 for any information to the schemes of the trust"

services = "Services"
last_updated = "Last Updated"
total_visitors = "Total Visitors"

ap_treasury_site = "AP Treasury Site"
aadhar_site = "Aadhar Site"
copyright_policy = "Copyright Policy"
hyperlink_policy = "Hyperlink Policy"
terms_conditions = "Terms and Conditions"
ayushman_bharat= "Ayushman Bharat"
accessibility_statement = "Accessibility Statement"
know_more = "Know More"
sitemap = "Sitemap"

hospitals = "Hospitals"
procedures = "Treatments"
speciality_search = "Speciality Search"
arogya_mitra = "Aarogya Mithra"

asri_app = "Aarogyasri App"
mitra_app = "Mithra App"
ehs_app = "EHS App"
nhsrc = "NHSRC"
mohfw = "MOHFW"
cohfw = "COHFW"
nppa_india = "NPPA India"

glossary = "Glossary"
screen_reader = "ScreenReader"
find="Find Us On"
links="Useful Links"
medical="Helpline/Grievances"
visitors="Visitor Count "
aasara="Aarogya Aasara"
treatments="Treatments Covered"
netwrk="Network Hospitals"

ayushmanBharat="Ayushman Bharat"

/>