<%@ include file="/heading.jsp" %>
<%@ include file="/top.jsp" %>

<%@ include file="/sidebar.jsp" %>
<%@ include file="/rightContent.jsp" %>


						 <h3 class="bordertitle text-dark">Archive (Old)</h3>
						
						   <ul class="tab">
							<li valign="top"><span>01.07.2014:</span>Supply of Headsets within ten (10) days with minimum of one (1) year Warranty with Replacement <a href="" target="_blank">(Click here for details) </a></li>
							<li valign="top"><span>21.06.2014:</span>Supply of various model Toners (Cartridges) HP/ Samsung Make to Aarogyasri Health Care Trust <a href="" target="_blank">(Click here for details) </a></li>
							<li valign="top"><span>16.06.2014:</span>Circular on time period validation for preauthorization(45 days),Surgery(100 days) and dischage updates(90 days) for AHCT <a href="" target="_blank">(Click here for details) </a></li>
							<li valign="top"><span>10.06.2014:</span>Supply of various model Toners (Cartridges) HP/ Samsung Make to Aarogyasri Health Care Trust <a href="" target="_blank">(Click here for details) </a></li>
							<li valign="top"><span>22.05.2014:</span>Circular for Services of NWHs to the Aarogyasri beneficiaries of both the states without interruption even after bifurcation <a href="" target="_blank">(Click here for details) </a></li>
							<li valign="top"><span>09.05.2014:</span>Identification of Contractor for carrying the renovation work to accommodate files storage optimizer and to construct partly glazed aluminum cabin work for AHCT<a href="" target="_blank">(Click here for details) </a></li>
							<li valign="top"><span>02.05.2014:</span>Identification of BPO Service Provider for integrated Call Center Services for 104 Sevakendram <a href="" target="_blank">(Click here for details) </a></li>
							<li valign="top"><span>16.04.2014:</span>NAM's Shufflings of 23 districts with effect from 17-04-2014,00:00 hrs <a href="" target="_blank">(Click here for details) </a></li>
							<li valign="top"><span>03.04.2014:</span>Guidelines to NWHs regarding Neurology (Ischemic Strokes and Hemorrhagic Strokes) <a href="" target="_blank">(Click here for details) </a></li>
							<li valign="top"><span>28.03.2014:</span>Circular for updating of online empanelment application by the network hospitals-limiting of time period from 90 days to 30 days <a href="" target="_blank">(Click here for details) </a></li>
							<li valign="top"><span>24.03.2014:23</span> Districts NTLs &amp; DTLs shuffling data for the month of Mar-14 with effect from 26-03-2014,00:00 hrs <a href="" target="_blank"> (Click Here for NTL Details) </a><a href="" target="_blank"> (Click here for DTL Details)</a></li>
							<li valign="top"><span>04.03.2014:</span>Guidelines to the NWHs regarding Orthopaedic/ Polytrauma Procedures <a href="" target="_blank">(Click here for details) </a></li>
							<li valign="top"><span>04.03.2014:</span>Suggestions to the Trust &amp; Panel doctors regarding Orthopaedic/ Polytrauma Procedures <a href="" target="_blank">(Click here for details) </a></li>
							<li valign="top"><span>03.03.2014:</span>Guidelines for Pediatric, Neonatal &amp; PICU Packages <a href="" target="_blank">(Click here for details) </a></li>
							<li valign="top"><span>01.03.2014:</span>Vacancy notification for District Coordinator - Medak District <a href="" target="_blank">(Click here for details) </a></li>
							<li valign="top"><span>27.02.2014:</span>Circular for Implementation of EHS - Opening of Seperate Joint Bank Account in the name of " District Collector or His/Her Nominee (Designation only) and the Superintendent" <a href="" target="_blank">(Click here for details) </a></li> 
							<li valign="top"><span>15.02.2014:</span>Bid Notification for Annual Maintenance Contract for Ductables and Split AC units in all the Trust locations <a href="" target="_blank">(Click here for details) </a></li> 
							<li valign="top"><span>13.02.2014:</span>Vacancy notification for District Coordinators <a href="" target="_blank">(Click here for details) </a></li> 
							<li valign="top"><span>13.02.2014:</span>Vacancy notification for District Managaer Nizamabad <a href="" target="_blank">(Click here for details) </a></li> 
							<li valign="top"><span>13.02.2014:</span>Vacancy notification for Joint Executive Officer Technical <a href="" target="_blank">(Click here for details) </a></li> 
							<li valign="top"><span>11.02.2014:</span>Bid notification for the work of Repair and Service of existing chairs in 104 Sevakendram <a href="" target="_blank">(Click here for details) </a></li> 
							<li valign="top"><span>10.02.2014:</span>Gudielines for Empanelment Department regarding Nephrologists Paramedical Staff and Duty Doctors <a href="" target="_blank">(Click here for details) </a></li> 
							<li valign="top"><span>10.02.2014:</span>Guidelines to NWH regarding maintenance Haemodialysis <a href="" target="_blank">(Click here for details) </a></li> 
							<li valign="top"><span>07.02.2014:</span>Addendum - Further Extension of time for Presentation of Bidders for Identification of Audit Firm for carrying the work of Internal Audit of AHCT <a href="" target="_blank">(Click here for details) </a></li> 
							<li valign="top"><span>01.02.2014:</span>Addendum Extension of time for Presentation of Bidders for Identification of Audit Firm for carrying the work of Internal Audit of AHCT <a href="" target="_blank">(Click here for details) </a></li> 
							<li valign="top"><span>01.02.2014:23</span> Districts NAMs shuffling data for the month of February-14 with effect from 04-02-2014. 00-00 hrs <a href="" target="_blank">(Click here for details) </a></li> 
							<li valign="top"><span>16.01.2014:</span>Circular for Regisration of Service Contract Agreement <a href="" target="_blank">(Click here for details) </a></li>
							<li valign="top"><span>10.01.2014:</span>Addendum for Hiring of Vehicles to the Officials of AHCT <a href="" target="_blank">(Click here for details) </a></li> 
							<li valign="top"><span>07.01.2014:</span>Vacancy notification for the post of JEO(Tech)<a href="" target="_blank">(Click here for details) </a></li> 
							<li valign="top"><span>31.12.2013:</span>Bid notification for Hiring of Vehicles for Officials of Aarogyasri Health Care Trust <a href="" target="_blank">(Click here for details) </a></li> 
							<li valign="top"><span>10.01.2014:</span>Bid notification for Identification of Audit Firm at Aarogyasri Health Care Trust <a href="http://www.eprocurement.gov.in/" target="_blank">(Click here for details) </a></li>
							<li valign="top"><span>24.12.2013:</span>Bid document for Fabrication and Decoration of the stall for displaying the Salient features of Aarogyasri and EHS.<a href="javascript:fn_EHS_features()">Click here for details </a></li>
							<li valign="top"><span>14.12.2013:</span> Integrated Supply of 50 KVA / 360 VDC Online UPS System with One Hour Battery Backup for AHCT with maintenance. <a href="javascript:fn_UPS_system()">Click here for details </a></li>
							<li valign="top"><span>21.12.2013:</span> Walk in interview for the post of Deputy Executive officer (Technical) on 28.12.2013 between 10.00 AM to 1.00 PM at Aarogyasri Health Care Trust <a href="javascript:fn_VacancyDyEO()">Click here for details </a></li>
							<li valign="top"><span>23.11.2013:</span> 23 Districts NAMs shuffling data for the month of NOV-13 with effect from 26-11-2013,00:00 hrs<a href="javascript:fn_NAM_suffeling()">Click here for details </a></li>
							<li valign="top"><span>03.10.2013:</span> Circular for Revision of Combination of Specialties for empanelment under Aarogyasri Scheme- Intimation to all the NWHs <a href="javascript:fn_circular_for_combination()">Click here for details </a></li>
							<li valign="top"><span>19.09.2013:</span> "AHCT-Revised Service Contract Agreement(2013-2016) between Aarogyasri Health Care Trust and Network Hospitals in Hyderabad - Authorisation to Joint Executive Officer(Admin) to execute and get register the SCA at Hyderabad" <a href="javascript:SCA_Hyd()">Click here for details </a></li>
							<li valign="top"><span>19.09.2013:</span> "AHCT-Revised Service Contract Agreement(2013-2016) between Aarogyasri Health Care Trust and Network Hospitals in Hyderabad - Permission to get the registration in the neighbouring districts of Telangana" <a href="javascript:SCA_TelNeighbour()">Click here for details </a></li>
							<li valign="top"><span>11.09.2013:</span> AHCT-Submission of Contact Agreement (2013-2016) by the Network Hospitals of Aarogyasri scheme - Extension of time up to September 15th, 2013 - Intimation - Reg. <a href="javascript:SubmissionofContractAgreement()">Click here for details </a></li>
							<li valign="top"><span>22.08.2013:</span>Circular for Empanelment of additional specialities Instistance of re-inspection fee from the NWHs.<a href="javascript:Circular_Emp_Specialties()">Click here for details </a></li>
							<li valign="top"><span>02.08.2013:</span>Circular on the extension of time for submission of SCA - Intimation - Reg.<a href="javascript:CircularSCA()">Click here for details </a></li>
							<li valign="top"><span>01.08.2013:</span>Circular for Submission of Claims pending at the time of delist of Network Hospitals by the Hospitals- certain instructions.<a href="javascript:DelistedPayments()">Click here for details </a></li>
							<li valign="top"><span>15.06.2013:</span>"Biometric authorisation of RAMCO's while raising preauthorisations and Patients biometric registration in RAMCO's login for IP cases."<a href="javascript:Circular_on_Biometric_Enrolment()">Click here for details </a></li>
							<li valign="top"><span>02.11.2013:</span>Integrated Supply of 50 KVA / 360 VDC Online UPS System with One Hour Battery Backup for AHCT with maintenance.<a href="javascript:UPS_Maintenance_Bod()">Click here for details </a></li>
							<li valign="top"><span>23.11.2013:</span>Vacancy notification for JEO(Technical) <a href="javascript:fn_JEO_Tech()"> Click here for details </a></li>
							<li valign="top"><span>23.11.2013:</span> Vacancy notification for DyEO(Non-Tech Accounts)<a href="javascript:fn_DyEO_NonTech()"> Click here for details </a></li>
							<li valign="top"><span class="date">06.11.2013:</span> Vacancy notification for the post of District Coordiantor Karimnagar District<a href="javascript:fn_Karimnagar_dist_coord()"> Click here for details </a><!--<a href="http://www.office.aarogyasri.gov.in//MCS/viewCareers.do" target="_blank" style="font-size:12px;font-weight:bold;"><img src="ASRI-images/applynow.png" alt="Apply Now" title="Apply Now"/></a>--></li>
							<li valign="top"><span>06.11.2013:</span>Walkin interview for the posts of Deputy Executive Officers (Technical) &amp; (Technical-Dental) on 18th November from 10.00AM to 01.00PM<a href="javascript:fn_tech_dental()"> (Click here for details)</a></li>
							<li valign="top"><span>22.10.2013:</span>Integrated Call Centre for 104 Sevakendram for a period of thirty six (36) months <a href="http://www.eprocurement.gov.in/" target="_blank">(Click here for details)</a></li>
							<li valign="top"><span>17.10.2013:</span>Walk-in-interview for the post of District Co-ordinator Karimnagar on 28th Oct 2013 between 10.00am to 1.00pm <a href="javascript:fn_Revised_CO_kharimnagar()"> (Click here for details)</a></li>
							<li valign="top"><span>30.09.2013:</span>AHCT-Non Submission of Contract Agreement(2013-2016) by the Network Hospitals of Aarogyasri Scheme -Keeping the payments on hold from October 15th,2013<a href="javascript:fn_Contract_NonSubmission()"> (Click here for details)</a></li>
							<li valign="top"><span>26.09.2013:</span>Vacancy notification for the post of Executives-104Sk<a href="javascript:fn_Executives_104sk()"> (Click here for details)</a></li>
							<li valign="top"><span>25.09.2013:</span>Walk-in-interview for the post of District Co-coordinator Karimnagar on 1st Oct 2013 between 10.00am to 1.00pm <a href="javascript:fn_Dist_co_coordinator_notification()"> (Click here for details)</a></li>
							<li valign="top"><span>24.09.2013:</span>"23 Districts NTLs &amp; DTLs shuffling data for the month of Sep13 with effect from 26.09.2013,00:00 hrs"<a href="javascript:fn_DTL_details()">(Click here for DTL's details)</a>&nbsp;<a href="javascript:fn_NTL_details()">(Click here for NTL's details)</a></li>
							<li valign="top"><span>23.09.2013:</span>Walk-in-Interview for the post of Deputy Executive Officer(Technical) on 01st October 2013 between 10.00AM to 01.00PM at Aarogyasri Health Care Trust <a href="javascript:fn_vacancies()">Click here for details</a></li>
							<li valign="top"><span>25.07.2013:</span>Circular for Package Pricing Orthopedic and Poly trauma opinion to be followed while processing the cases. <a href="javascript:Orthopedic_Polytrauma_Pricing()">Click here for details</a></li>
							<li valign="top"><span>15.07.2013:</span>Circular for Package Pricing-CT Surgeons,Cardiologists opinion - To be followed while processing the cases. <a href="javascript:Circular_CT()">Click here for details</a></li>
							<li valign="top"><span>11.07.2013:</span>Circular for Imposing of Exemplary penalty on NWH for Omissions and Commissions such as money collection from the Aarogyasri beneficiaries and deficiency in Service -Intimation. <a href="javascript:IMPOSING_EXEMPLARY_PENALTY_ON_NWH()">Click here for details</a></li>
							<li valign="top"><span>02.07.2013:</span>Submission of Basic information by the existing NWHs for enabling the Trust to empanel the hospitals under EHF scheme.<a href="javascript:circular_EHF()">Click here for Circular,&nbsp;</a><a href="javascript:DECLARATIOn_LETTER_for_EHS()">Click here for Declaration letter for EHS,&nbsp;</a><a href="javascript:EHS_hospitals()">Click here for EHS module to existing hospitals.</a></li>
							<li valign="top"><span>29.06.2013:</span>Circular for NABH accreditation by National Accrediataion Board for Hospital and Health Care Providers taken as parameter payment of 2% over and above the basic package price. <a href="javascript:Circular_NABH()">Click here for details</a></li>
							<li valign="top"><span>29.06.2013:</span> Implementation of New package prices for Aarogyasri Healthcare Scheme <a href="javascript:Input_code_book()">Click here for Input Code Book,&nbsp;</a><br><a href="javascript:Standard_schedule_rates()">Click here for Standard Schedule of Rates for Medical inputs,&nbsp;</a><a href="javascript:Current_Procd_ures_list()"> Click here for Final Therapy Prices.</a></li>
							<li valign="top"><span>28.06.2013:</span>"Circular on Aarogyasri Package Prices". <a href="javascript:Circular_prices()">Click here for details"</a></li>
							<li valign="top"><span>24.06.2013:</span>"Revised Service Contract Agreement of Network Hospitals.(<a href="javascript:Revised_Contract_062013()">Click here for Revised Service Contract Agreement)</a>and Power delegation to DCs for registration of SCA <a href="javascript:SCA_registration_062013()">(Click here for SCA registration powers delegated to DCs)".</a></li>
							<li valign="top"><span>06.06.2013:</span>"Circular on the renewal of Service Contract Agreement (2013-2016) w.e.f 01.04.2013 for the NWHs."<a href="javascript:NWH_renewal_SCA()">Click here for details</a></li>
							<li valign="top"><span>23.05.2013:</span>"Inclusion of Aadhaar CARD for proof of nativity/residence for CMCO Referral card"<a href="javascript:Cmco_Circular()">Click here for details</a></li>
							<li valign="top"><span>06.09.2013:</span>NAM's shuffling of 23 districts with effect from 11-09-2013, 00:00 hrs.<a href="javascript:Shuffling_1109()">Click here for details</a></li>
							<li valign="top"><span>04.09.2013:</span>Walk-in-Interview for selection of Deputy Executive Officer (Technical) on 11th September 2013 between 10.00 A.M to 01.00P.M at Aarogyasri Health Care Trust. <a href="javascript:Vacancy_DEO_0409()">Click here for details</a></li>
							<li valign="top"><span>22.08.2013:</span>Bid Notification for "Providing of Annual Maintenance Contract of Emerson Precision A/C System for AHCT for a period of two (2) years"<a href="javascript:AMC_EmersioPrecision_AC()">Click here for details</a></li>
							<li valign="top"><span>19.08.2013:</span>Bid notification for "Construction of side walls around canteen with GI sheets, RCC sink cum platform with polished granite and water leakages in toilets in 104 Sevakendram for fifteen (15) days."<a href="javascript:CivilWorks_104()">Click here for details</a></li>
							<li valign="top"><span>08.08.2013:</span> "Integrated Call Centre for 104 Sevakendram for a period of thirty six (36) months." <a href="http://www.eprocurement.gov.in/" target="_blank">Click here for details</a></li>
							<li valign="top"><span>26:08:2013:</span> Walk-in-Interview for selection of Deputy Executive Officer (Technical) on 31st August 2013 between 10.00 A.M to 01.00P.M at Aarogyasri Health Care Trust.<a href="javascript:Circular_Vacancy_Notification()">Click here for details</a></li>
							<li valign="top"><span>09:08:2013:</span>"Providing of Annual Maintenance Contract of Emerson Precision A/C System for AHCT for a period of two (2) years" <a href="javascript:AMC_of_Precision_AC()">Click here for details</a></li>
							<li valign="top"><span>06:08:2013:</span> Addendum for the work of "Supply of Printing Material for AHCT and its branches" <a href="javascript:PrintingAddendum()">Click here for details</a></li>
							<li valign="top"><span>06:08:2013:</span> Addendum for the work of "Providing of Stationary Items for AHCT and its branches" <a href="javascript:StationaryAddendum()">Click here for details</a></li>
							<li valign="top"><span>30:07:2013:</span> "Providing of Supply of Printing Material for AHCT and its branch offices i.e. Trust office, Jambagh and 104 office for a period of twenty four (24) months." <a href="javascript:PrintingDocument2()">Click here for details</a></li>
							<li valign="top"><span>30:07:2013:</span>"Providing of Stationary items for AHCT and its branch offices i.e. Trust office, Jambagh and 104 office for a period of twenty four (24) months." <a href="javascript:StationaryDocument2()">Click here for details</a></li>
							<li valign="top"><span>28:07:2013:</span>"Renewal of Fortigate Firewall and Analyzer along with comprehensive support for Aarogyasri Health Care Trust and its offices from the date of commencement of Contract for a period of 3 years." <a href="http://www.eprocurement.gov.in/" target="_blank">Click here for details</a></li>
							<li valign="top"><span>28:07:2013:</span>"Printing and Dispatching of CM Feedback Letters, Collecting and Scanning Feedback Letters, Surfing the Newspaper both English and Telugu (All AP Editions), Segregation of Positive and Adverse News Items, Uploading the News Items in the Aarogyasri Portal for a period of thirty six (36) months" <a href="javascript:CM_Feedback_Letters()">Click here for details</a></li>
							<li valign="top"><span>29:01:2013:</span> "Bid Notification for "Integrated Call Centre Services - 104 Sevakendram". <a href="http://www.eprocurement.gov.in/" target="_blank">Click here for details</a></li>
							<li valign="top"><span>13:07:2013:</span>"Supply of Printing Material for AHCT and its branches". <a href="javascript:PrintingDocument()">Click here for details</a></li>
							<li valign="top"><span>13:07:2013:</span>"Providing of Stationary Items for AHCT and its branches". <a href="javascript:StationaryDocument()">Click here for details</a></li>
							<li valign="top"><span>05:07:2013:</span> "Renewal of Fortigate Firewall and Analyzer along with comprehensive support for Aarogyasri Health Care Trust and its offices from the date of commencement of Contract for a period of 3 years". <a href="http://www.eprocurement.gov.in/" target="_blank">Click here for details</a></li>
							<li valign="top"><span>04:01:2013:</span> Empanelment of Dental and Psychiatrty Hospitals for Employee Health Fund Scheme <a href="javascript:CIRCULAR_FOR_DENTAL_PSYCHIATRY_EMPANELMENT()">Click here for details</a></li>
							<li valign="top"><span>11.01.2013:</span> Revision of Combination of specialties for empanelment under Aarogyasri Scheme- Intimation to all the NWHs <a href="javascript:NWHs_Circular()">Click here for details</a></li>
							<li valign="top"><span>18.01.2013:</span> Grievance Department-Capturing of complete Patient addrees at the time of Registration-Instructions to the NAMs and Network Team Leaders (NTLs) <a href="javascript:INSTRUCTIONS_NAM_NTL()">Click here for details</a></li>
							<li valign="top"><span>02.02.2013:</span> Revised Guidelines on claims settlement and other issues <a href="javascript:Claims_guidelines()">Click here for details</a></li>
							<li valign="top"><span>28.02.2013:</span>Circular for Certain mandatory documents to be furnished by the network hospitals <a href="javascript:NHW_HOSP_Furnish()">Click here for details</a></li>
							<li valign="top"><span>19.03.2013:</span>Any Patients admitted paediatric age group can be treated under Aarogyasri <a href="javascript:paediatric()">Click here for details</a></li>
							<li valign="top"><span>24.06.2013:</span>NAM's shuffling of 23 districts with effect from 25-06-2013, 00:00 hrs. <a href="javascript:SHUFFLING_DATA_062013()">Click here for details</a></li>
							<li valign="top"><span>07.06.2013:</span>Walk-in Interview for post of Deputy Executive Officer (Technical) on 21st June 2013 between 10:00AM to 1:00PM at Aarogyasri Health Care Trust <a href="javascript:Dy_EO_Tech()">Click here for details</a>. </li>
							<li valign="top"><span>03.06.2013:</span>"Notification for the work of "Supply of Drawings &amp; Printing Material for AHCT and its branch offices for a period of twenty four (24) months" <a href="http://www.eprocurement.gov.in/" target="_blank">Click here for details</a></li>
							<li valign="top"><span>01.06.2013:</span>""Providing of Stationery for AHCT and its branch offices i.e. Trust office, Jambagh and 104 office for a period of twenty four (24) months"<a href="http://www.eprocurement.gov.in/" target="_blank">Click here for details</a></li>
							<li valign="top"><span>02.05.2013:</span>Bid notification for "Providing Annual Maintenance service of Desktops, Laptops, Printers, Scanners, Routers, AV Equipment, Telecom for AHCT and its branches i.e., YSR Bhavan, Jambagh, Koti and 23 District Offices and where ever required by the Trust" <a href="http://www.eprocurement.gov.in/" target="blank">Click here for details</a>. </li>
							<li valign="top"><span>26.04.2013:</span>Aaarogyasri Health Care Trust Package Prices. <a href="javascript:ICD_CODES_OF_OP_PACKAGES()">ICD Codes of OP Packages,&nbsp;</a><a href="javascript:ICD_CODES_OF_SURGICAL()">ICD Codes of Surgical Packages,&nbsp; ,</a><a href="javascript:ICD_CODES_OF_MEDICAL()">ICD Codes of Medical Packages.</a></li>
							<li valign="top"><span>23.04.2013:</span>Circular for AHCT-Trust Cancelled Cases Permission to update any pending claims of all NWHs. <a href="javascript:Circular_CancelledCases_One()">Click here for details</a></li>
							<li valign="top"><span>16.03.2013:</span>"Revised Service Contract Agreement of Network Hospitals (<a href="javascript:Revised_Service_Contract_Agreement()">Click here for Revised Service Contract Agreement </a>)and Power delegation to DCs for registration of SCA (<a href="javascript:SCA_registration_powers_delegated_to_DCs()">Click here for SCA registration powers delegated to DCs</a>)". </li>
							<li valign="top"><span>10:05:2013:</span>Walkins for DYEO(Technical) on 16th May of 2013 between 10am to 2pm <a href="javascript:dy_eo_news()">Click here for details</a>. </li>
							<li valign="top"><span>04.05.2013:</span>Bid notification for "Supply of Full HD LED Smart display TV for Aarogyasri Health Care Trust and its offices"<a href="http://www.eprocurement.gov.in/" target="blank">Click here for details</a>. </li>
							<li valign="top"><span>20.04.2013:</span>Maintenance and Development of Aarogyasri IT Application, and Preparation of IT Road Map for Aarogyasri Health Care Trust.<a href="http://www.eprocurement.gov.in/" target="blank">Click here for details</a>. </li>
							<li valign="top"><span>23.04.2013:</span>Bid notification for "Supply of Drawings &amp; Printing Material for AHCT and its branches".<a href="http://www.eprocurement.gov.in/" target="blank">Click here for details</a>. </li>
							<li valign="top"><span>12.04.2013:</span>Printing and Dispatching of CM Feedback Letters, Collecting and Scanning Feedback Letters, Surfing the Newspaper both English and Telugu (All AP Editions), Segregation of Positive and Adverse News Items, Uploading the News Items in the Aarogyasri Portal <a href="http://www.eprocurement.gov.in/" target="blank">Click here for details</a>. </li>
							<li valign="top"><span>12.04.2013:</span>NAM's Shufflings of 23 districts with effect from 15-04-2013,00:00 hrs. (<a href="javascript:shuffling_list_for_portal_updatioon()">Click here for Details </a>). </li>
							<li valign="top"><span>03.04.2013:</span>EHF training programme schedule for Net work Hospitals and NTLs on 6th and 7th of April 2013 at "Dr.Marri Chenna Reddy Human Resource Development Instuite of A.P , Auditoriuam, Road No.25, Jubilee Hills" (<a href="javascript:EHf_TRAINING_CIRCULAR()">Click here for Circular </a>) (<a href="javascript:hospitals()">Click here for Hospital details </a>)(<a href="javascript:NTL_TRAINING_SCHEDULE()">Click here for NTLs </a>) </li>
							<li valign="top"><span>11.03.2013:</span>23 Districts DTLs &amp; NTLs shuffling data for the month of March13 with effect from 15.03.2013,00:00 hrs.<a href="javascript:DTLs_shuffling()">Click here for DTLs Shuffling &amp; </a><a href="javascript:NTLs_shuffling()">NTLs Shuffling Data Details </a></li>
							<li valign="top"><span>26.03.2013:</span>"Providing of House Keeping Services for AHCT and its branches i.e., YSR Bhavan, Jambagh and Koti for Aarogyasri Health Care Trust".<a href="http://www.eprocurement.gov.in" target="_blank">Click here for details</a></li>
							<li valign="top"><span>27.02.2013:</span>"Network Security Firewall, Supply,Installation,Commissioning and Support" at Jambagh Location for Aarogyasri Health Care Trust.<a href="http://www.eprocurement.gov.in" target="_blank">Click here for details</a></li>
							<li valign="top"><span>27.02.2013:</span> Bid Document for "Procurement of Logistics for Aarogyasri Health Care Trust" <a href="javascript:Logistics_Tenders()">Click here for details</a></li>
							<li valign="top"><span>05.02.2013:</span> NAMs Shuffling with effect from 06-02-2013 00:00 Hours. <a href="javascript:Updated_FINAL_SHEET_Shuffling()">Click here for details</a></li>
							<li valign="top"><span>04.02.2013:</span> "Procurement of Aprons to Aarogyamithras working for Aarogyasri at 23 districts". <a href="http://www.eprocurement.gov.in" target="_blank">Click here for details</a></li>
							<li valign="top"><span>08.01.2013:</span> "Procurement of Aprons to Aarogyamithras working for Aarogyasri at 23 districts". <a href="http://www.eprocurement.gov.in" target="_blank">Click here for details</a></li>
							<li valign="top"><span>5:12:2012:</span>Guidelines on claims settlement and other issues<a href="javascript:Guidelines_Claims_settlement_other_issues()"> Click here for details</a></li>
							<li valign="top"><span>05.01.2013:</span>Revised Guidelines on claims settelment and other issues<a href="javascript:claim_settlement()">Click here for details</a></li>
							<li valign="top"><span>11.01.2013:</span>Short tender notice for "Annual Maintenance Service of desktops consists of preventive and corrective maintenance including necessary repairs of parts". <a href="javascript:Tender_AMC_of_Systems()">Click here for details</a></li>
							<li valign="top"><span>21.01.2013:</span>Addendum for Bid Notificaiton (Annual Maintenance Service of desktops consists of preventive and corrective maintenance including necessary repairs of parts for AHCT) Lr No. AHCT/Admn/F 19(Desktops)/2248-R/2012-13, dated: 08.01.2013" <a href="javascript:Annual_Maintenance_Desktops()">Click here for details</a></li>
							<li valign="top"><span>22.01.2013:</span>"Addendum for Cancellation of Bid Notificaiton (Annual Maintenance Service of desktops consists of preventive and corrective maintenance including necessary repairs of parts for AHCT) Lr No. AHCT/Admn/F 19(Desktops)/2248-R/2012-13, dated: 08.01.2013" <a href="javascript:cancel_Annual_Maintenance_Desktops()">Click here for details</a></li>
							<li valign="top"><span>03.01.2013:</span> "Addendum for Bid Notification (Setting up of a 500 Ltr/hr Reverse Osmosis System at AHCT) No.AHCT/ADMN/F 31/2248-N/2012-13,dated:27.12.2012." <a href="javascript:Water_Addendum_two()">Click here for details</a></li>
							<li valign="top"><span>03.01.2013:</span> "Addendum for Bid Notification (Hiring of Vehicles for Officials of Aarogyasri Health Care Trust ) No.AHCT/ADMN/F 31/2248-N/2012-13,dated:29.12.2012." <a href="javascript:Vehicle_Addendum_one()">Click here for details</a></li>
							<li valign="top"><span>02.01.2013:</span> Bid Notification for " Setting up of a 500 Ltr/hr Reverse Osmosis System" <a href="javascript:RO_System_Specification()">Click here for details</a></li>
							<li valign="top"><span>28.12.2012:</span> Bid Notification for "Hiring of Vehicles for Officials of Aarogyasri Health Care Trust " <a href="javascript:Tender_vehicles()">Click here for details</a></li>
							<li valign="top"><span>27.12.2012:</span> Bid Notification for "Setting up of a Water Distillation Plant at AHCT" (Cancellation) <a href="javascript:Water_Plant_bid()">Click here for details</a></li>
							<li valign="top"><span>22:12:2012:</span> e-Tender Notification for "Internet Service Providers for providing 200 MBPS MPLS-VPN Connectivity in a ring at Hyderabad to all its six locations of AHCT" For Tender filing Visit e-procurement website <a href="http://www.eprocurement.gov.in" target="_blank">Click here for details</a></li>
							<li valign="top"><span>06:12:2012:</span> Bid Notification for "Supply and Installation of 400 Amps auto change over panel suitable for 200 KVA Caterpillar DG set, Oulioor, Weather proof" <a href="javascript:Generator()">Click here for details</a></li>
							<li valign="top"><span>06:12:2012:</span> Bid Notification for "De-commissioning, Shifting &amp; Commissioning of 2 X 40 KVA UPS from Liberty to Jambagh, duly supply of batteries" <a href="javascript:UPS_Tender()">Click here for details</a></li>
							<li valign="top"><span>22:11:2012:</span> NAMs Shuffling with effect from 26-11-2012 00:00 Hours <a href="javascript:ShufflingDistricts()">Click here for details</a></li>
							<li valign="top"><span>08:10:2012:</span> Deployment of new online work flow module for pre authorization and claims process with effect for 10.10.2012 <a href="javascript:deployCircular()">Click here for details</a></li>
							<li valign="top"><span>25:09:2012:</span> Circular on coverage of treatment for orphans and destitute under Aarogyasri Scheme <a href="javascript:circular_on_orphans_coverage()">Click here for details</a></li>
							<li valign="top"><span>17:09:2012:</span> Reimbursement of cost of pre-registration investigation <a href="javascript:Circular170912()">Click here for details</a></li>
							<li valign="top"><span>12:09:2012:</span> Instructions to all Network Hospitals for Updation of Expertise Details <a href="javascript:online_expertise_details()">Click here for details</a></li>
							<li valign="top"><span>07:09:2012:</span> Guidelines on Vascular procedures under Aarogyasri Scheme <a href="javascript:VascularGuidelines()">Click here for details</a></li>
							<li valign="top"><span>30.08.2012:</span> Revised Health Camp Policy. <a href="javascript:HCPolicy()">Click here for details</a></li>
							<li valign="top"><span>25.08.2012:</span> AarogyasriHealthCare Trust- Clarification on the package of Maintenance Haemodialysis <a href="javascript:Circular_haemodialysis()">Click here for details</a></li>
							<li valign="top"><span>09.08.2012:</span> Carrying of 938 procedures by Trust alone - Intimation <a href="javascript:Trust938Procedures()">Click here for details</a></li>
							<li valign="top"><span>07.08.2012:</span> Circular - Instructions to NWH's to conduct Mega Health Camps with effect from August -12 <a href="javascript:NWH_Circular()">Click here for details</a></li>
							<li valign="top"><span>02.08.2012:</span> Guidelines for the Gynaecological Oncology cases under Aarogyasri Shceme <a href="javascript:Gye_guidelines()">Click here for details</a></li>
							<li valign="top"><span>05.07.2012:</span> Circular - Procedure to invoke penalty clause with effect from 21-07-2012 <a href="javascript:exemplary_penalty()">Click here for details</a></li>
							<li valign="top"><span>14.03.2012:</span> Biometric registration of Aarogyasri patients in the Government Network Hospitals-Exemptions for certain cases <a href="javascript:Guidelines_for_patientBiometry()">Click here for details</a></li>
							<li valign="top"><span>12.03.2012:</span> Guidelines for Biometric Regsitration and Discharges of Patients (Circular to field) and User manuals<a href="javascript:circulartofield()">Click here for Details </a> | <a href="javascript:manual_for_capture_finger_impression()">Click here for Manuals </a></li>
							<li valign="top"><span>15.12.2012:</span>Bid Notification for "Hiring of Vehicles for Officials of Aarogyasri Health Care Trust" <a href="javascript:Circular_for_Vehicles()">Click here for Circular</a>, <a href="javascript:Vehicles_Bid()">Click here for details</a></li>
							<li valign="top"><span>06:12:2012:</span>e-Tender Notification for "Internet Service Providers for providing 200 MBPS MPLS-VPN Connectivity in a ring at Hyderabad to all its six locations of AHCT " For Tender filing Visit e-procurement website <a href="http://www.eprocurement.gov.in" target="_blank"> Click here</a></li>
							<li valign="top"><span>18.07.2012:</span> Phase IV &amp; V NWHs Service Contract agreement extended for a period of three months w.e.f 18.07.2012<a href="javascript:Circular_New_Cantract_Agreement()"> Click here</a></li>
							<li valign="top"><span>03:11:2012:</span> e-Tender Notification by AHCT for BPO service Providers for Providing Services to AHCT. This document will be visible from 08.11.2012, 7.00 AM. For Tender filing Visit e-procurement website<a href="http://www.eprocurement.gov.in" target="_blank"> Click here</a></li>
							<li valign="top"><span>12:09:2012:</span> Hyderabad NAMs Shuffling with effect from 15th Sep 2012 00:00hrs <a href="javascript:HydShufflingTCS()"> Click here</a></li>
							<li valign="top"><span>26:11:2012:</span> Vacancy Notification for DYEO and PS <a href="javascript:Vacancy5097()"> Click here</a></li>
							<li valign="top"><span>16:11:2012:</span> Vacancy Notification <a href="javascript:Vacancy4898()"> Click here</a></li>
							<li valign="top"><span>16:09:2012:</span> e-Tender Notification by AHCT for BPO service Providers for Providing Services to AHCT. For Tender filing Visit e-procurement website<a href="http://www.eprocurement.gov.in" target="_blank"> Click here</a></li>
							<li valign="top"><span>01:11:2012:</span> Vacancy Notification <a href="javascript:Vacancy()" target="_blank"> Click here</a></li>
							<li valign="top"><span>29:09:2012:</span> e-Tender(Short Tender) Notification for Providing fingerprint biometric based Health Cards to employees/pensioners and their dependent family members for Aarogyasri Health Care Trust for tender filing visit e-Procurement website <a href="http://www.eprocurement.gov.in" target="_blank"> Click here</a></li>
							<li valign="top"><span>08.10.2012:</span> Vacancy Notification <a href="javascript:doc017()"> Click here</a></li>
							<li valign="top"><span>07.09.2012:</span> e-Tender Notification for Providing fingerprint biometric based Health Cards to employees/pensioners and their dependent family members for Aarogyasri Health Care Trust for tender filing visit e-Procurement website <a href="http://www.eprocurement.gov.in" target="_blank"> www.eprocurement.gov.in</a></li>
							<li valign="top"><span>24.09.2012:</span>Vacancy Notification <a href="javascript:DOC015()">Click here for Details </a></li>
							<li valign="top">12.09.2012:Selection of 104 employees (Phase VIII)<a href="javascript:SelectedCandidates104()">Click here for Details</a></li>
							<li valign="top">18.08.2012:e-Tender Notification for Establishment of Office at Jambagh,M.J.Road,Hyderabad and Providing Security Services for Aarogyasri Health Care Trust for tender filing visit e-Procurement website <a href="http://www.eprocurement.gov.in" target="_blank"> www.eprocurement.gov.in</a></li>
							<li valign="top">25.07.2012:Modified District Managers Shuffling with effect from 26-07-2012 <a href="javascript:DM_shuffling_list()">Click here for Details </a></li>
							<li valign="top">20.07.2012:Bid Notification for providing accommodation for the Office of District Coordinator in all Districts except Khammam District is extended upto 25.07.2012 <a href="javascript:Accomidation_bid_Circular()">Click here for Details </a></li>
							<li valign="top">08.08.2012:Vacancy Notification <a href="javascript:vacdoc()">Click here for Details </a></li>
							<li valign="top">06.06.2012:Alert notice to the Network Hosptials on collection of money for self styled publications misusing the name of Aarogyasri Trust <a href="javascript:pandc()">Click here for Details </a></li>
							<li valign="top">07.05.2012:Imposing of Exemplary Penalty up to Ten times against erring NWHS for Omissions &amp; Commissions such as Collection of money from Patients &amp; Deficiency in Service - Communication -Reg <a href="javascript:DOC002()">Click here for Details </a></li>
							<li valign="top">03.05.2012:Guidelines on Clinical Photographs<a href="javascript:Circular_clinical()">Click here for Details </a></li>
							<li valign="top">16.04.2012:Modification of Guidelines for Cochlear implantation Programme <a href="javascript:Modification_of_Guidelines_for_Cochlear()">Click here for Details </a></li>
							<li valign="top">03.07.2012:District Managers Shuffling with effect from 26-07-2012<a href="javascript:dm_Shuffling()">Click here for Details </a></li>
							<li valign="top">19.03.2012: Biometric device vendor details <a href="javascript:Biometric_vendor_details()">Click here for Details </a></li>
							<li valign="top">08.05.2012: Revised Empanelment requirement guidelines <a href="javascript:Revised_Guidelines_For_Hospitals_Emp()">Click here for Details </a></li>
							<li valign="top">29.05.2012: Requirement of Outsourcing Agency for the Vigilance Services in Andhraparadesh <a href="javascript:Vigilance_Dept()">Click here for Details </a></li>
							<li valign="top">12.06.2012: DTLs Shuffling with effective from 01-07-2012 <a href="javascript:DTL()">Click here for Details </a></li>
							<li valign="top">25.06.2012: Warning on collection of Money from beneficiaries <a href="javascript:Warning_collection_Money()">Click here for Details </a></li>
							<li valign="top">03.07.2012: Circular issued to the NWH with regard to empanelment of specialities <a href="javascript:circular_to_nwh()">Click here for Details </a></li>
							<li valign="top">25.06.2012: Bid notification for providing accommodation for the Office of District Coordinator in all Districts except Khammam District <a href="javascript:Notice_BID()">Click here for Details </a></li>
							<li valign="top">19.06.2012: Vacancy Notification for the post of District Coordinators and Medical Officers CMCO Peripheral Centers <a href="javascript:Vacancy_DC()">Click here for Details </a></li>
							<li valign="top">29.05.2012: Bid Document for providing accommidation for the office of DC's in 21 Districts <a href="javascript:bid29()">Click here for Details </a></li>
							<li valign="top">02.05.2012: Aarogyasri Health Care Trust - Change in E-mail Services - Intimation <a href="javascript:Instructions_Zimbra()">Click here for Details </a></li>
							<li valign="top">02.05.2012: Declaration Addendum to SCA of Phase IV &amp; V <a href="javascript:Declaration()">Click here for Details </a></li>
							<li valign="top">05.06.2012: Schedule of interviews for the post of Health Advisors on 11th,12th,and 13th of June2012 <a href="javascript:Binder05()">Click here for Details </a></li>
							<li valign="top">12.06.2012: NTLs Shuffling with effective from 16-06-2012 <a href="javascript:NTL()">Click here for Details </a></li>
							<li valign="top">18.06.2012: List of selected candidates for the post of Health Advisor in 104 Sevakendram, Koti, Hyderabad <a href="javascript:DOC10()">Click here for Details </a></li>
							<li valign="top">10.04.2012: Alert Note issued- Reg misuse of Trust officials name in order to influence funtionaries of Trust <a href="javascript:GENERALCIRCULARFORNWH()">Click here for Details </a></li>
							<li valign="top">7.05.2012: Revised Vacancy Notification for the post of Manager IT <a href="javascript:Notification16()">Click here for Details </a></li>
							<li valign="top">15.05.2012: Addendum of Electrical, interior, Wood, Civil &amp; HVAC works <a href="javascript:Addendum15()">Click here for Details </a></li>
							<li valign="top">14.05.2012: e - Procurement for Providing HVAC works for Aarogyasri Health Care Trust at Jambagh, Hyderabad <a href="javascript:FinalHVAC4()">Click here for Details </a></li>
							<li valign="top">14.05.2012: e - Procurement for Providing Interior, Wood &amp; Civil works for Aarogyasri Health Care Trust at Jambagh, Hyderabad for Details <a href="javascript:FinalInterior4()">Click here for Details </a></li>
							<li valign="top">14.05.2012: e - Procurement for Providing Electrical works for Aarogyasri Health Care Trust at Jambagh, Hyderabad <a href="javascript:FinalElectrical4()">Click here for Details </a></li>
							<li valign="top">09.05.2012: Bid for providing Stationery <a href="javascript:Final_Stationery()">Click here for Details </a></li>
							<li valign="top">09.05.2012: Bid for providing Printing Material <a href="javascript:Final_Printing()">Click here for Details </a></li>
							<li valign="top">09.05.2012: Minutes of the Pre-Bid Meeting for Electrical, Interior, Wood &amp; Civil works and HVAC Works <a href="javascript:MOM_PB()">Click here for Details </a></li>
							<li valign="top">20.04.2012: Bid Document for data entry, scanning, processing work <a href="javascript:Bid_Document_DATA_ENTRY()">Click here for Details </a></li>
							<li valign="top">09.05.2012: Addendum - III to the Electrical works, HVAC Works, Interior, Wood &amp; Civil Works at Jambagh <a href="javascript:Electrical_addendum3()">Click here for Details </a></li>
							<li valign="top">05.05.2012: Addendum - II to the Electrical works, HVAC Works, Interior, Wood &amp; Civil Works at Jambagh <a href="javascript:addendum_may()">Click here for Details </a></li>
							<li valign="top">26.04.2012: Addendum to the Electrical works, HVAC Works, Interior, Wood &amp; Civil Works at jambagh <a href="javascript:Addendum_Electrical_HVAC_Interior()">Click here for Details </a></li>
							<li valign="top">24.04.2012: Providing Electrical works for Aarogyasri Health Care Trust at Jambagh, Hyderabad <a href="javascript:Final_Electrical_Bid_Jambagh()">Click here for Details </a></li>
							<li valign="top">24.04.2012: Providing HVAC works for Aarogyasri Health Care Trust at Jambagh, Hyderabad <a href="javascript:Final_HVAC_Bid_Jambagh()">Click here for Details </a></li>
							<li valign="top">24.04.2012: Providing Interior, Wood &amp; Civil works for Aarogyasri Health Care Trust at Jambagh, Hyderabad <a href="javascript:Final_Interior_Bid_Jambagh()">Click here for Details </a></li>
							<li valign="top">28.04.2012: Vacancy Notifications <a href="javascript:vacany_notification_new()">Click here for Details </a></li>
							<li valign="top">11.04.2012: Action Plan for Prajapatham-2012 <a href="javascript:Action_plan_prajapadam()">Click here for Details </a></li>
							<li valign="top">19.04.2012: Vacancy Notification. <a href="javascript:Vac_Notification()">Click here for Details </a></li>
							<li valign="top">14.04.2012:Bid document for Procurement of house keeping services . <a href="javascript:Binder1()">Click here for Details </a></li>
							<li valign="top">27.04.2012: Addendum3 to House keeping Bid document. <a href="javascript:Addendum3_Housekeeping()">Click here for Details </a></li>
							<li valign="top">25.04.2012: Addendum-2 for the house keeping bid document. <a href="javascript:Adendum_HouseKeeping_Final()">Click here for Details </a></li>
							<li valign="top">25.04.2012: Addendum to House Keeping Bid Document. <a href="javascript:HK_Addendum()">Click here for Details </a></li>
							<li valign="top">25.04.2012: Addendum to the Interior works at jambagh. <a href="javascript:Interior()">Click here for Details </a></li>
							<li valign="top">25.04.2012: Addendum to the HVAC works at jambagh. <a href="javascript:HVAC()">Click here for Details </a></li>
							<li valign="top">25.04.2012: Addendum to the Electrical works at jambagh. <a href="javascript:Electrical()">Click here for Details </a></li>
							<li valign="top">20.04.2012: Walk in interviews for Doctors. <a href="javascript:Walkin_DYEO_Tech()">Click here for Details </a></li>
							<li valign="top">15.03.2012: Network Hospital Aarogyamithra Shuffling Data With Effect from 16th March 2012, 00:00 Hrs. <a href="javascript:Districts15_Final_Shuffle_Data()">Click here for Details </a></li>
							<li valign="top">03.04.2012: Selection of 104 employees (Phase VI) <a href="javascript:employees_PhaseVI_104()">Click here for Details </a></li>
							<li valign="top">10.04.2012: Intimation - Reg Beware of middlemen and Brokers <a href="javascript:SPECIFIC_CIRCULAR_FOR_NWH()">Click here for Details </a></li>
							<li valign="top">21.03.2012 : Selected Employees and Last date for joining of 104 <a href="javascript:Selected_Employees_104()">Click here for Details </a> </li>
							<li valign="top">12.03.2012 : Addendum - II to the Bid Document for Advetising agency <a href="javascript:Addendum_II()">Click here for Details </a> </li>
							<li valign="top">07.03.2012 : Addendum to the Bid Document for Advetising agency<a href="javascript:Adendum()">Click here for Details </a> </li>
							<li valign="top">07.03.2012 : Establishment of CMCO Peripheral Centres in 6 places in the districts - Guidelines issued.<a href="javascript:CircularCMCOPeripheralCentres()">Click here for Details </a> </li>
							<li valign="top">03.03.2012 : Sealed Tender are invited from Accredited Advertising agency to prepare art work design and to produce one corporate film of 12 mins and 8 Training film each of 20 mins duration. The last date for submission of tender is 20-03-2012 by 3.00 PM in the AHCT Office, Jubilee Hills, Hyderabad.<a href="javascript: Bid_Doc_Advertising_004()">Click here for Details </a> </li>
							<li valign="top">07.03.2012 : Sealed tendor for providing vechiles on hire basis reg<a href="javascript: Bid_Hiring_Vehicles_001()">Click here for Details </a> </li>
							<li valign="top">13.02.2012 : Covering Letter together with the proforma of Standard Case Sheet for all Net workhospitals,effective for pre-authorisations raised from 00:00 hrs of 15.02.2012.<a href="javascript: Standard_Case_Sheet()">Click here for Details </a> </li>
							<li valign="top">20.01.2012 : NOTICE INVITING BID FOR ARCHITECTURE CONSULTANT.<a href="javascript: NotificationforDeputyExecutive()">Click here for Details </a> </li>
							<li valign="top">30.01.2012 : Addendum for NOTICE INVITING BID FOR ARCHITECTURE CONSULTANT.<a href="javascript: NotificationforDeputyExecutive()">Click here for Details </a></li>
							<li valign="top">20.01.2012 : Vacancy Notification for Deputy Executive Officer(Tech &amp; Non tech.<a href="javascript: NotificationforDeputyExecutive()">Click here for Details </a> </li>
							<li valign="top">20.01.2012 : Selected 104 Employees (Phase-III) Last date for joining 27.01.2012.<a href="javascript: SelectedEmployeesDOJPIII()">Click here for Details </a> </li>
							<li valign="top">18.01.2012 : Work shop on Regression methods using EXCEL and STATA to be held on 9.02.2012 to 11.02.2012.<a href="javascript: Workshop()">Click here for Details </a></li>
							<li valign="top">17.01.2012 : Selected Employees (Phase _II) last date for joining 20.01.2012.<a href="javascript: SelectedEmployeesDOJ()">Click here for Details </a></li>
							<li valign="top">07.01.2012 : VACANCY NOTIFICATION for District Coordinator &amp; Vigilance Officer.<a href="javascript: NOTIFICATIONforDistrictCoordinator()">Click here for Details </a></li>
							<li valign="top">07.01.2012 : 104 Call Centre 2nd Phase Recruitment - list of selected candidates for the posts of Health Advisors &amp; Counseling officers as per applying roster points to the merit list .<a href="javascript: CallCentrePhaseRecruitment()">Click here for Details </a></li>
							<li valign="top">01.12.2011 : Modified Guidelines to raise Preauthorizations.<a href="javascript: PreauthRevisedGuidelines()">Click here for Details </a> List of Procedures/Therapies &amp; Number of preauthorizations allowed within 30 days.<a href="javascript: PREAUTHRAISED()">Click here for Details!!! </a> </li>
							<li valign="top">02.12.2011 : Provisional List of selected Candidates (HAO &amp; CO) for 104 Call Centre<a href="javascript:Recruitment104()">Click here for Details </a> </li>
							<li valign="top">12.12.2011 : Selected 104 Employees last date for joining 15.12.2011. <a href="javascript:EmployeesDOJ()">Click here for Details </a> </li>
							<li valign="top">03.12.2011 : Walk - in Interview for MBBS. <a href="javascript:WalkIn()">Click here for Details </a> </li>
							<li valign="top">08.11.2011 : Rachabanda-II Schedule. <a href="javascript:RachabandaSchedule()">Click here for Details </a> </li>
							<li valign="top">08.11.2011 : Renewal of Aarogyasri Health Insurance Scheme in 5 districts of Phase-II - Meeting of the IRDA approved Insurance Companies on 18.11.2011 at 3:00 P.M. The draft bid is made available for your perusal and comment.<a href="javascript: MeetingOfIRDA()">Click here for Details </a> </li>
							<li valign="top">10.11.2011 : Vacancy Notification for the post of Executive(PMU)<a href="javascript:PostOfExecutive()">Click here for Details </a> </li>
							<li valign="top">14.11.2011 : Vacancy Notification for the post of Executive(PMU)<a href="javascript:PostOfExecutive()">Click here for Details </a> </li>
							<li valign="top">21.11.2011 : Aarogyasri Health Care Trust - conducting Interviews to the ex-employees of 104 Call Centre <a href="javascript:CallCenterInterviews()">Click here for Details </a><span>List of ex-employees</span><a href="javascript:ListOfEmployees()">Click here for Details </a></li>
							<li valign="top">22.10.2011 : Short Tender Notification for Providing Vehicles on Hire.<a href="javascript:NotificationforProvidingVehicles()">Click here for Details </a> </li>
							<li valign="top">14.10.2011 : Service Contract Agreement for Phase IV(3R) &amp; Phase V (3R) to be executed by Network Hospitals with Star Health.<a href="javascript:HealthServicesContract()">Click here for Details </a> </li>
							<li valign="top">29.09.2011 : Emergency Telephonic Intimation Numbers of Insurer.<a href="javascript:EmergencyTelephonicIntimation()">Click here for Details </a> </li>
							<li valign="top">29.09.2011 : Short Tender Notification for Providing Vehicles on Hire. <a href="javascript:TenderNotificationVehicles()">Click here for Details </a></li>
							<li valign="top">28.09.2011 : Intimation of Airtel CUG Connections of Insurer.<a href="javascript:AirtelCUGConnections()">Click here for Details </a></li>
							<li valign="top">28.09.2011 : Vacancy Notification for the post of Deputy Executive Officer (Non-Tech). <a href="javascript:DeputyExecutiveOfficer()">Click here for Details </a></li>
							<li valign="top">24.09.2011 : Vacancy Notification for District Coordinators. <a href="javascript:DistrictCoordinators()">Click here for Details </a></li>
							<li valign="top">22.09.2011 : Addendum to Internet Service Provider Selection- Short Tender Notice. <a href="javascript:addendumMplsVPN()">Click here for Details </a></li>
							<li valign="top">19.09.2011 : Addendum to the Vehicle Tender Notification. <a href="javascript:AddendumVehicleTndrNotf()">Click here for Details </a></li>
							<li valign="top">19.09.2011 : Addendum to 104 Call Centre Staffing. <a href="javascript:AddendumCallCentre()">Click here for Details </a></li>
							<li valign="top">16.09.2011 : Revised Contract Agreement For Phase IV &amp; Phase V. <a href="javascript:RevisedContractAgreement()">Click here for Details </a></li>
							<li valign="top">16.09.2011 : Revised Internet Service Provider Selection- Short Tender Notice. <a href="javascript:ShortTenderNotice()">Click here for Details </a></li>
							<li valign="top">08.09.2011 : Collection of Contract Agreement for Phase IV &amp; V from the Network Hospitals <a href="javascript:Instruction_District_Cord()">Click here for Details</a></li>
							<li valign="top">08.09.2011 : Guidelines for Anaesthesiology procedures for conducting Laparoscopic surgeries under the scheme. <a href="javascript:Guide_Anaesthesiology()">Click here for Details </a></li>
							<li valign="top">06.09.2011 : Notice Inviting Bid for 104 Call Centre Staffing. <a href="javascript:BPOBidDocument()">Click here for Details </a></li>
							<li valign="top">06.09.2011 : Tender for Hire Vehicles. <a href="javascript:TenderforHireVehicles()">Click here for Details </a></li>
							<li valign="top">04.09.2011 : Vacancy Notification. <a href="javascript:VacancyNotification()">Click here for Details </a></li>
							<li valign="top">29.08.2011 : Intimation of Airtel CUG Connections of Insurer.<a href="javascript:AirtelCUGConnections()">Click here for Details </a> </li>
							<li valign="top">29.08.2011 : Cancellation of Tender Notification issued for providing IT Infrastructure Managed Services. <a href="javascript:Cancel_TenderNotification()">Click here for Details </a></li>
							<li valign="top">29.08.2011 : Download contract agreeement for Phase IV &amp; Phase V. <a href="javascript:ContractAgreementIV_V()">Click here for Details </a></li>
							<li valign="top">27.08.2011 : Guidelines for District Coordinators &amp; Divisional Team Leaders for conducting Health Camps in the PHC's. <a href="javascript:GuidelinesDCTL()">Click here for Details </a></li>
							<li valign="top">22.08.2011 : Addendum to IT Infrastructure Managed Services Bid- Revised schedule of the Bidding Process. <a href="javascript:addendum()">Click here for Details </a></li>
							<li valign="top">22.08.2011 : Exemption of Health Camps for the Network Hospitals of Phase IV &amp; V. <a href="javascript:HealthCampsExmptn()">Click here for Details </a></li>
							<li valign="top">17.08.2011 : Notice Inviting Proposal for providing IT Infrastructure Managed Services. <a href="javascript:ITMS()">Click here for Details </a></li>
							<li valign="top">17.08.2011 : Change in last date of submission of the Electrical Tender issued on 12-08-2011. <a href="javascript:NewTenderForm()">Click here for Details </a></li>
							<li valign="top">12.08.2011 : Tender Form for Electrical Works at Aarogyasri Building, Koti,Hyderbad. <a href="javascript:TenderForm()">Click here for Details </a></li>
							<li valign="top">12.08.2011 : Guidelines to Govt. Institutions/Hospitals in 10 districts of Phase IV &amp; V regarding reservation of 133 procedures. <a href="javascript:Binder()">Click here for Details </a></li>
							<li valign="top">09.08.2011 : Issuing revised guidelines for conducting Health camps in 10 districts <a href="javascript:Letter_Healthcamps()">Click here for Details </a></li>
							<li valign="top">09.08.2011 : Health camp Policy Phase IV &amp; V districts. <a href="javascript:Health_Camp_Policy()">Click here for Details </a> <img src="ASRI-images/New_icons_47.gif">!!! </li>
							<li valign="top">02.08.2011 : Updated / Modified list of 133 Procedures Reserved for Government Hospitals. <a href="javascript:List_of_Procedures_updated()">Click here for Details </a> <img src="ASRI-images/New_icons_47.gif">!!! </li>
							<li valign="top"> 27.07.2011 : <a href="javascript:Vacancy_Notifications()">Vacancy Notifications</a> | <a href="javascript:Application_Proforma()">Application Proforma</a></li>
							<li valign="top"> 27.07.2011 : Reserved Packages for Government Hospitals in 10 Districts (Phase IV &amp; Phase V) from 1st August 2011. <a href="javascript:List_of_Procedures()">List of 133 procedures in Govt Hospitals</a> | <a href="javascript:Final_Procedures()">Proposed Action Plan</a> !!! </li>
							<li valign="top"> 25.07.2011 : Emergency Telephonic Intimation Numbers of Network Hospitals has been changed for Trust run procedures (AS-II) to 7702789866.<a href="javascript:Telephonic_Intimation()">Click Here for Details </a> !!! </li>
							<li valign="top"> 04.07.2011 : Addendum to the Bid notiifcation for support service provider for Trust administered scheme of bid notification No.AST/ F51 / PIV &amp; PV /2011-12, dated 26.06.2011. <a href="javascript:Addendum_new()">Click Here for Details </a> !!! </li>
							<li valign="top">02.07.2011: Addendum for Insurance bid notification No.AST/ F51 / PIV &amp; PV (3R)/2011-12, dated 26.06.2011. <a href="javascript:Addendum()">Click Here for Details </a>Click Here for Details !!! </li>
							<li valign="top">01.07.2011: Scheme Experience for Bidders. <a href="/ASRI/EXT_IMAGES/documents/schemeanalysis.xls">(Scheme Analysis Report)</a> | <a href="/ASRI/EXT_IMAGES/documents/Surgery-Incidence-Report.xls">(Surgery Incidence Report) </a> !!! </li>
							<li valign="top">29.06.2011: Schedule time of prebid Meet.<a href="javascript:SchdleBidTime()">Click Here for Details </a>Click Here for Details !!! </li>
							<li valign="top">27.06.2011: Bidding Document For Engaging IRDA Approved Insurance Companies/Insurers for the Implementation of Aarogyasri Health Insurance Scheme to the Beneficiaries of 10 Districts in Andhra Pradesh P-IV&amp;P-V (3rd Renewal) <a href="javascript:Bidding_Document()">Click Here for Details </a> !!! </li>
							<li valign="top">27.06.2011:Bidding Document For Provision of support services for Aarogyasri Health Scheme for BPL families in 10 Districts of Adilabad, Hyderabad, Kurnool, Vizianagaram, Visakhapatnam, Nizamabad, Khammam, Warangal, Guntur and Krishna in Andhra Pradesh. <a href="javascript:BID_Document_Support_Services()">Click Here for Details </a>!!! </li>
							<li valign="top">02.06.2011: For Vacancy Position: Notification for Vacancy position of various categories in Aarogyasri Health Care Trust. </li>
							<li valign="top">02.06.2011: For Panel Doctors : " Notification for Empanelment of Specialist Doctors. " </li>
							<li valign="top">15.05.2011: Instructions to Network Hospitals - Updation of Expertise Workflow in Preauthorisation. <a href="javascript:InstrctnToNetwrkHospsExperlitls()">Click here for Details</a></li>
							<li valign="top">15.05.2011: Instructions to Network Hospitals - Updation of Expertise details. <a href="javascript:Exprlietails()">Click here for Details</a></li>
							<li valign="top">28.04.2011: Aarogyasri crossed 1 Million surgeries/Therapies. <a href="javascript:StatusReportMillion()">Click here for Details</a></li>
							<li valign="top">28.04.2011: Exemption of Taxable service Under Section 65(105)(zzzzo) of the Finance Act 1994 Vide GOI Notification No.30/2011 dated 25th April 2011.<a href="javascript:ServiceTax()">Click here for Details.</a></li>
							<li valign="top">25.04.2011: Online Preauthorization Request Form (PRF) updated for Pending Cases - Instructions to Network Hospitals. <a href="javascript:PreauthRequestForm()">Click here for Details.</a></li>
							<li valign="top">21.04.2011: New Aarogyamithra Shuffling details with effect from 26/04/2011, 00:00 hrs. <a href="javascript:AprilNWHAarogyamithra()">Click here for Details.</a></li>
							<li valign="top">20.04.2011: Instructions issued by CTW for accessing Aarogyasri by boarders of TW Educational Institutions.<a href="javascript:CircularByCWT()">Click here for Details.</a></li>
							<li valign="top">19.04.2011: Delegates from Government of Arunachal Pradesh visit Aarogyasri Health Care Trust.<a href="javascript:PressNoteArunachalPradesh()">Click here for Details.</a></li>
							<li valign="top">03.04.2011: Renewal of Scheme in 8 districts - Phase I (4th Renewal) &amp; Phase III (3rd Renewal) - Instructions to Network Hospitals.<a href="javascript:LetterTo_Hospitals_PhaseI4R_PhaseIII3R()">Click here for Details.</a></li>
							<li valign="top">03.04.2011: MOU with Network Hospitals Phase I (4th Renewal) &amp; Phase III (3rd Renewal).<a href="javascript:MOU_PhaseI4R_PhaseIII3R_DraftAprovl()">Click here for Details.</a></li>
							<li valign="top">31.03.2011: Delegation led by Dr.A.K.Walia, Hon'ble Minister of Health &amp; Family Welfare, Govt. of N.C.T. of Delhi visited Aarogyasri Health Care Trust.<a href="javascript:Press_note_Delhi_Team_visit()">Click here for Details.</a></li>
							<li valign="top">28.03.2011 : Aarogyasri Crossed 43 lakh screenings and 9.5 lakh surgeries/therapies. !!! </li>
							<li valign="top">26.03.2011: Guidelines for Coverage of Aarogyasri for New born babies in TAP card holding families. <a href="javascript:TAP_Newborn()">Click here for Details.</a></li>
							<li valign="top">15.03.2011: Pre -Bid meet for Renewal of Aarogyasri Health Insurance Scheme in 8 districts of Phase-I and Phase-III on 16.03.2011 at 3.00 P.M. in conference hall of Aarogyasri Health Care Trust, YSR Bhavan, Road. No.46, Jubilee Hills, Hyderabad:<br> Invitation to IRDA registered non life Insurance Companies.<a href="javascript:PreBidMeet16March()">Click here for Details.</a></li>
							<li valign="top">21.02.2011: Aarogyamithra Shuffling with effect from 26.02.2011, 00:00 hrs. <a href="javascript:AarogyamithraShufflingFeb2011()">Click here for Details.</a></li>
							<li valign="top">20.02.2011: Heartfelt condolences for Ms. Syed Rahana Begum and Mr.Guddi Bala Subramanyam, Aarogyamithras of Kurnool..<a href="javascript:heartfelt_condolences_Aarogyamithras()">Click here for Details.</a></li>
							<li valign="top">09.02.2011 : Aarogyasri Crossed 41 lakh screenings and 9 lakh surgeries/therapies. !!! </li>
							<li valign="top">26.01.2011: Action Plan Rachabanda 2011.<a href="javascript:ActionPlanRachabanda()">Click here for Details.</a></li>
							<li valign="top">22.01.2011: Instructions to Network hospitals on Aarogyasri coverage to Temporary BPL Household Card holders. <a href="javascript:BPLcardholders()">Click here for Details.</a></li>
							<li valign="top">22.01.2011: Guidelines to Temporary BPL Household Card Holders for availing Aarogyasri benefit. <a href="javascript:Temparary_Card_Guidelines()">Click here for Details.</a></li>
							<li valign="top">14.01.2011 : Aarogyasri Crossed 40 lakh screenings and 8.7 lakh surgeries/therapies. </li>
							<li valign="top">29.12.2010 : Aarogyamithra Shuffling with effect from 01.01.2011, 00:00 hrs. <a href="javascript:Mithra_shuffle_Jan()">Click here for Details.</a></li>
							<li valign="top">28.12.2010 : Aarogyasri Crossed 39 lakh screenings and 8.5 lakh surgeries/therapies. </li>
							<li valign="top">24.12.2010 : Service Tax U/S 65 (105) (zzzzo) of Finance Act 1994 -Instructions To Corporate / Private Network Hospitals. <a href="javascript:ServiceTaxLetter()">Click here for Details.</a></li>
							<li valign="top">09.11.2010 : Aarogyasri Crossed 37 lakh screenings and 8 lakh surgeries/therapies. </li>
							<li valign="top">3.12.2010 : Renewal of Aarogyasri Health Insurance Scheme in 5 Districts of West Godavari, East Godavari, Chittoor, Nalgonda and Rangareddy - Phase II (3rd Renewal) from 00:00 hrs of 05.12.2010 - Intimation to Network Hospitals. <a href="javascript:PhaseII_IIIrd_Renewal()">Click here for Details.</a></li>
							<li valign="top">1.12.2010 : Hon'ble Chief Minister put first signatures for clearing Aarogyasri Renewal proposal and in letters to Aarogyasri beneficiaries enquiring about their health. <a href="javascript:cm_signature()">Click here for Details.</a></li>
							<li valign="top">30.10.2010 : Aarogya Mithra Shuffling with effect from 02.11.2010, 00:00 hrs. <a href="javascript:StarAarogyasriShufflingData()">Click here for Details.</a></li>
							<li valign="top">26.10.2010 : Comprehensive Guidelines on Cochlear Implant Surgery and AV Therapy procedure <a href="javascript:CochAVTheraphy()">Click Here for Details</a></li>
							<li valign="top">21.10.2010 : Revised guidelines for Opthalmology procedures <a href="javascript:GuidOpthmlgy()()">Click here for Details.</a></li>
							<li valign="top">20.10.2010 : Heartfelt condolences to Late Mr G Sai Prasad, Regional Coordinator, Nizamabad <a href="javascript:condolences()">Click here for Details.</a></li>
							<li valign="top">21.10.2010 : Comprehensive Guidelines on Cochlear Implant Surgery and AV Therapy procedure <a href="javascript:CochAVTheraphy()">Click here for Details.</a></li>
							<li valign="top">21.10.2010 : Revised guidelines for Opthalmology procedures <a href="javascript:GuidOpthmlgy()">Click here for Details.</a></li>
							<li valign="top">18.10.2010 : Instructions and guidelines to Network Hospitals - Health Camps. <a href="javascript:CircularNew()">Click Here for Details </a></li>
							<li valign="top">06.10.2010 : G.O. Rt. No. 1344: HM&amp;FW Department-Guidelines for utilization of amounts received by the Government Hospitals through Aarogyasri Scheme-Amendment. <a href="javascript:GO1344()">Click Here for Details </a></li>
							<li valign="top">02.10.2010 : Shuffling of TLs, RCs &amp; AAMs effective from 4.10.2010.<a href="Districts.html" target="_blank"> Click Here for Details </a></li>
							<li valign="top">02.10.2010 : Shuffling of AMs &amp; DGMs effective from 7.10.2010.<a href="javascript:AM_DGM_Shuflng_efct_frm_0710()"> Click Here for Details </a></li>
							<li valign="top">29.09.2010 : Aarogyasri Crossed 35 lakh screenings and 7.5 lakh surgeries/therapies. </li>
							<li valign="top">29.08.2010 : Maharashtra Chief Secretary &amp; Officials visit Aarogyasri Health Care Trust. <a href="javascript:MaharashtraCSVisit()"> Click Here for Details </a></li>
							<li valign="top">15.09.2010 : Instructions for proper video recording of counselling session.<a href="javascript:WEBEXCounsellingdocument()"> Click Here for Details </a></li>
							<li valign="top">31.08.2010 : Guidelines for selection criteria for procedures under Orthopaedics and Neurosurgery. <a href="javascript:guidelines_Orthopaedic_Neuro()"> Click Here for Details </a></li>
							<li valign="top">29.08.2010 : Maharashtra Chief Secretary &amp; Officials visit Aarogyasri Health Care Trust. <a href="javascript:MaharashtraCSVisit()"> Click Here for Details </a></li>
							<li valign="top"> 27.08.2010 :Installation Of Biometrics System in Network Hospitals. <a href="javascript:AarogyasriBiometrics()"> Click Here for Details </a></li>
							<li valign="top">20.08.2010 :New Shifts for Aarogyamithra Effective from 23rd August 2010. <a href="javascript:MithraShift_Aug()"> Click Here for Details </a></li>
							<li valign="top">07.08.2010 : Aarogyasri Crossed 34 lakh screenings and 7 lakh surgeries/therapies. </li>
							<li valign="top">16.06.2010 : Instructions to Network Hospitals on Follow up. <a href="javascript:Followup()">Click Here for Details </a>!!! </li>
							<li valign="top">11.06.2010 : New Shifts for Aarogyamithra Effective from 14th June 2010. <a href="javascript:MithraShift_June()"> Click Here for Details </a> !!! </li>
							<li valign="top">19.05.2010 : Gynaecology and Obstetrics procedures - Rationalisation of Packages effective from 00.00 hrs of 21.05.2010. <a href="javascript:GynecologyProcedure()">Click Here for Details </a> !!! </li>
							<li valign="top">22.04.2010 : Modified workflow for Surgery/Treatment schedule update. <a href="javascript:Surgery_Treatment()">Click Here for Details </a> !!!</li>
							<li valign="top">21.04.2010 : Revised guidelines for Gynaecology and Obstetrics procedures under Aarogyasri <a href="javascript:Gynecology()">Click Here for Details </a> !!! </li>
							<li valign="top">19.04.2010 :Action plan for Aarogyasri - Prajapatham 2010 . <a href="javascript:Prajapatham()"> Click Here for Details </a> !!! </li>
							<li valign="top">14.04.2010: Modified workflow for discharge,death and clinical photo updating/uploading. <a href="javascript:discharge_upload()">Click Here for Details </a> !!! </li>
							<li valign="top"><img src="ASRI-images/arrow.gif" align="top"></li>
							<li valign="top">03.04.2010: Instructions to Network Hospitals. <br> Renewal of Aarogyasri Insurance Scheme(Aarogyasri I &amp; Aarogyasri II) for BPL families in 3 districts of Anantapur,Mahboobnagar,Srikakulam (Phase I,3rd Renewal) from 00:00 hrs of 5th April 2010 and in 5 districts of Medak,Karimnagar,Prakasam,SPS Nellore and Kadapa (Phase III ,2nd Renewal) from 00:00 hrs of 15th April 2010. <a href="javascript:NetworkHospital()">Click Here for Details </a> !!! </li>
							<li valign="top">03.04.2010: MOU Phase I (3R) &amp; Phase III (2R). <a href="javascript:MOU_PHASE()">Click Here for Details </a> !!! </li>
							<li valign="top">26.03.2010: New Shifts for Aarogyamithra Effective from 2nd April 2010. <a href="javascript:MithraShift_April()">Click Here for Details </a>!!! </li>
							<li valign="top">25.03.2010 : Emergency Telephonic Intimation-Instructions to Network Hospitals. <a href="javascript:Emergency_Telephonic()">Click Here for Details </a> !!! </li>
							<li valign="top">19.03.2010 : Instructions to Network Hospital-liS Non Deduction &amp; Lower Deduction u/s 197 of IT Act 1961. <a href="javascript:liS_NonDeduction()"> Click Here for Details </a> !!! </li>
							<li valign="top">02.03.2010 : Implementation of liS in Aarogyasri - Instructions to Network Hospitals. <a href="javascript:liS_Implementation()">Click Here for Details </a> !!! </li>
							<li valign="top">02.02.2010: G.O. Rt. No. 134: Health, Medical &amp; Family Welfare Department - Aarogyasri Health Insurance Scheme – Norms for billing and Guidelines for utilization of amounts received by the Government Hospitals under Aarogyasri scheme. <a href="javascript:gortNo134()">Click Here for Details </a></li>
							<li valign="top">02.02.2010: New Shifts for Aarogyamithra Effective from 2nd February 2010. <a href="javascript:MithraShift()">Click Here for Details </a></li>
							<li valign="top">29.01.2010 Maharashtra Health Minister &amp; Officials visit Aarogyasri Health Care Trust to study the scheme. <a href="javascript:Press_note()"> Click Here for Details </a></li>
							<li valign="top">23.01.2010 : Aarogyasri Crosses 27 lakh screenings and 5 lakh surgeries/therapies. <br><a href="javascript:Note_LandMark()">Click Here for Details </a></li>
							<li valign="top">18.01.2010 : liS on Aarogyasri Payments U/s 197J of Income Tax Act 1961. <a href="javascript:lis_doc()">Click Here for Details </a></li>
							<li valign="top">07.01.2010 : New guidelines for selection criteria for procedures under ENT surgeries. <a href="javascript:ENT_Surgeries()">Click Here for Details </a></li>
							<li valign="top">06.01.2010 : Circular on liS to Network Hospitals. <a href="javascript:liS_NWHospitals()"> Click Here for Details </a></li>
							<li valign="top">24.12.2009 : Dr Y.S.R BHAVAN INAUGURATED Aarogyasri Health Care Trust Office Complex Opp Dr B.R Ambedkar Open University Road No:46, Jubilee Hills,Hyderabad-500033. <a href="javascript:Bhavan()">Click Here for Details </a></li>
							<li valign="top">02.12.2009 : New Shifts for Aarogyamithra Effective from 2nd December 2009. <a href="javascript:getMithraShifts()">Click Here for Details </a></li>
							<li valign="top">21.11.2009 : AAROGYASRI crossed 4.5 LAKH surgeries/therapies mark.</li>
							<li valign="top">14.10.2009 : Tributes to our late chairman Dr.Y.S.Rajasekhara Reddy. <a href="javascript:getYSRTributes()">Click Here for Details </a></li>
							<li valign="top">29.09.2009: Journalist (Working/Retired) Scheme under CMRF-Guidelines to Network Hospitals. <a href="javascript:getJournalistGuidlines()"> Click Here to Download </a></li>
							<li valign="top">24.09.2009: Single Login for each Unique Aarogyasri User and additional Login Id's for RAMCO's,AMCCO's and Billing Head. <a href="javascript:Singleloginsignon()"> Click Here for Details</a></li>
							<li valign="top">09.08.2009 : AAROGYASRI crossed 3.5 LAKH surgeries/therapies mark. </li>
							<li valign="top">28.07.2009: Guidelines for Enhancement of Packages. <a href="javascript:EnhancementPkgs()"> Click Here for Details</a></li>
							<li valign="top">17.07.2009 : Treatment status update in medical management cases. <a href="javascript:Treatmentstatus()"> Click Here for Details</a></li>
							<li valign="top">05.07.2009 : Shifts for Aarogyamithra. <a href="javascript:MithraShifts()"> Click Here for Details</a></li>
							<li valign="top">03.07.2009 : AAROGYASRI reached surgeries worth 1000 crores. </li>
							<li valign="top">02.06.2009; Hon'ble Minister for Aarogyasri,Health Insurance, 108,104 and Medical Infrastructure visits Aarogyasri Health Care Trust Office </li>
							<li valign="top">20.02.2009: Total number of surgeries/therapies crossed 2 lakh today.</li>
							<li valign="top">02.02.2009 : " Sri Pradip Kumar Agarwal, IAS assumed charge as Executive Vice Chairman, Aarogyasri Health Care Trust." </li>
							<li valign="top">14.11.2008: Aarogyasri expanded with 77 new procedures taking total number of procedures covered to 940.</li>
							<li valign="top">14.11.2008: 121 Follow-up packages introduced.</li>
							<li valign="top">31.10.2008: 9th Board of Trustees Meeting chaired by honourable Chief Minister.</li>
							<li valign="top">13.06.2008: Cabinet ministers of Government of Karnataka visits Trust to study Aarogyasri Community Health Insurance Scheme </li>
							<li valign="top">Cancellation of 30 days old Pre-authorisations. <a href="javascript:CancellationDoc()"> Click Here for Details</a></li>
							<li valign="top">New Login for Aarogyasri Portal &amp; Aarogyasri Messaging Services. <a href="javascript:msgService()">Click Here.</a></li>
							<li valign="top">New Guidelines for selection of cases,strengthening of pre authorisations and claims process for Genitourinary procedures. <a href="javascript:GuidelinesGenitourinary()"> Click Here for Details </a></li>
							<li valign="top">Online updation of hospital information - Last Date 30th June 2009. <a href="javascript:HospEmpanelment()">Click Here for Details</a></li><!-- 	
								 <li valign="top">New guidelines for selection criteria for procedures under 
								   Gynaecology and Obstetrics. <a href="javascript:GuidelinesGynaecology()">Click Here 
									 for Details</a>
								 </li>
								-->
							<li valign="top">New guidelines for selection criteria for procedures under Cardiology and Cardiothoracic surgery. <a href="javascript:GuidelinesCardiology()">Click Here for Details</a></li>
							<li valign="top">User manual for updation of 'ON-BED' patients effective from 2nd March 09. <a href="javascript:OnbedPatientsManual()">Click Here for Details and New Module.</a></li>
							<li valign="top">Addition and Rationalisation of Packages effective from 00:00 hrs of 1st March 09. <a href="javascript:PackageEffMarch1st()">Click Here for Details.</a></li><!-- 
								 <li valign="top">All enhancement requests should be mailed to <A href="mailto:enhancements@aarogyasri.org">
									 enhancements@aarogyasri.org</A>. <a href="javascript:ClitlsforEnhancementRequests()">Click Here to view contacts.
								 </li>
								-->
							<li valign="top">"Revised guidelines on Cochlear Implantation Surgery and AV Therapy". <a href="javascript:openCochAttachment()">Click Here</a></li>
							<li valign="top">Expansion of Aarogyasri w.e.f 00:00 hours of 14th Nov 08. <a href="javascript:Guidelines1()">Click Here.</a></li>
							<li valign="top">List of documents to be provided along with case sheet of the Patients.<a href="javascript:openAttachment4()">Click Here</a></li>
							<li valign="top">Certain Instructions to the Network hospitals on eligibility criteria of the beneficiaries.<a href="javascript:openAttachment3()">Click Here</a></li>
							<li valign="top">New Premises for the office of the Insurer. <a href="javascript:Premises()"> Click Here for Details</a></li>
							<li><span class="date">15.12.2012:</span> Bid Notification for "Fabrication and Decoration of the stall for displaying the Salient features of Aarogyasri Health Care Trust" <a href="javascript:Fabrication_Decoration()">Click here for details</a></li>
							<li><span class="date">15.12.2012:</span> "Setting up of a Water Distillation Plant at Aarogyasri Health Care Trust" <a href="javascript:WaterDistillationPlant()">Click here for details</a></li>
							<li><span class="date">15.12.2012:</span> Bid Notification for "Internal Audit (Reconciliation) for Aarogyasri Health Care Trust" <a href="javascript:Internal_Audit()">Click here for details</a></li>
						   </ul>


<%@ include file="/last.jsp" %>