<%@ include file="/heading.jsp" %>
<%@ include file="/top.jsp" %>

<%@ include file="/sidebar.jsp" %>
<%@ include file="/rightContent.jsp" %>


    <h3 class="bordertitle text-dark">Notification Tender And Circular</h3>
    <ul>
             <li>"Tender document for printing of posters" <a href="https://115.124.110.149/documents/d/guest/1-1" target="_blank">(Click here for Details)</a>&nbsp; </li>
             <li>" Addendum document for Identification of Service Provider for supply of manpower (Security &amp; Housekeeping)" <a href="https://115.124.110.149/documents/d/guest/2" target="_blank">(Click here for Details)</a>&nbsp; </li>
             <li>"Tender document for Identification of Service Provider for supply of manpower (Security &amp; Housekeeping) " <a href="https://115.124.110.149/documents/d/guest/3" target="_blank">(Click here for Details)</a>&nbsp; </li>
             <li>"Tender document for Identification of Service Provider for (AMC) Annual maintenance of 56Nos. of Air Conditioners of Dr.YSR Aarogyasri Health Care Trust for a period of Twelve (12) months " <a href="https://115.124.110.149/documents/d/guest/4" target="_blank">(Click here for Details)</a>&nbsp; </li>
             <li>"Corrigendum-II &amp; III Document for e-tender for supply of manpower to Dr.YSR Aarogyasri Health Care Trust, Chuttugunta, Guntur " <a href="https://115.124.110.149/documents/d/guest/5" target="_blank">(Click here for Details)</a>&nbsp; </li>
             <li>"Corrigendum-I Document for e-tender for supply of manpower to Dr.YSR Aarogyasri Health Care Trust, Chuttugunta, Guntur " <a href="https://115.124.110.149/documents/d/guest/6" target="_blank" title="Click here for details">(Click here for details)</a></li>
             <li>e-tender for supply of manpower to Dr.YSR Aarogyasri Health Care Trust, Chuttugunta, Guntur <a href="https://115.124.110.149/documents/d/guest/7" target="_blank">(Click here for Details)</a>&nbsp; </li>
             <li>Corrigendum-II Document for Inviting Proposals for Selection of IT Service Provider and Medical Kits <a href="https://115.124.110.149/documents/d/guest/8" target="_blank">(Click here for Details)</a>&nbsp; </li>
             <li>"Dr.Dr.YSR AarogyasriT Bid queries and responses - Clarifications for Inviting Proposals for Selection of IT Service Provider and Medical Kits(Tender No.Dr.YSR Aarogyasri/PMU-IT/F852/IT Tender/2017-18 )" <a href="https://115.124.110.149/documents/d/guest/9" target="_blank">(Click here for Details)</a>&nbsp; </li>
             <li>Corrigendum Document for Inviting Proposals for Selection of IT Service Provider and Medical Kits <a href="https://115.124.110.149/documents/d/guest/10" target="_blank">(Click here for Details)</a>&nbsp; </li>
             <li>Tender Document for Inviting Proposals for Selection of IT Service Provider and Medical Kits <a href="https://115.124.110.149/documents/d/guest/11" target="_blank" title="Click here for details">(Click here for details)</a>. </li>
             <li style="font-weight:bold">Corrigendum Document for appointment of internal auditor <a href="https://115.124.110.149/documents/d/guest/12" target="_blank" title="Click here for details">(Click here for details)</a></li>
             <li style="font-weight:bold">Corrigendum Document for appointment of Statutory auditor. <a href="https://115.124.110.149/documents/d/guest/13" target="_blank" title="Click here for details">(Click here for details)</a></li>
             <li><span class="date">16.06.2017</span>: Tender Document for appointment of internal auditor <a href="https://115.124.110.149/documents/d/guest/14" target="_blank">(Click here for details)</a>&nbsp; <img alt="" src="/documents/10181/0/animated-new.png"></li>
             <li><span class="date">16.06.2017</span>: Tender Document for appointment of Statutory auditor <a href="https://115.124.110.149/documents/d/guest/15r" target="_blank">(Click here for details)</a>&nbsp; <a href="/documents/10181/38823/Internal+Audit.pdf" style="font-size: 12.8px;" target="_blank"> <img alt="" src="/documents/10181/0/animated-new.png"> </a></li>
             <li><span class="date">02.06.2017</span>: Corrigendum - I on Tender notification No. "Letter No. Dr.YSR AarogyasriT/HR/590/2017: Date - 26.05.2017 <a href="https://115.124.110.149/documents/d/guest/16r" target="_blank">(Click here for details)</a></li>
             <li><span class="date">24.05.2017</span>:Tender Document for Supply,Installation and Commissioning of 2x60 KVA UPS <a href="https://115.124.110.149/documents/d/guest/15" target="_blank">(Click here for details)</a></li>
             <li>Corrigendum on Tender No.Dr.YSR Aarogyasri/PMU-IT/F4035/IT Tender/2015-16 Dated:25-Nov-2016, Corrigendum-VII <a href="https://115.124.110.149/documents/d/guest/16" target="_blank">(Click here for details)</a></li>
             <li><span class="date">12.01.2017</span>: Revised Bid Schedule (Tender No.Dr.YSR Aarogyasri/PMU-IT/F4035/IT Tender/2015-16 Dated:23-Dec-2016) Corrigendum-VI <a href="https://115.124.110.149/documents/d/guest/17" target="_blank">(Click here for details)</a>&nbsp; </li>
             <li><span class="date">10.01.2017</span>: Dr.Dr.YSR AarogyasriT Bid queries and amendments -- Clarifications (Tender No.Dr.YSR Aarogyasri/PMU-IT/F4035/IT Tender/2015-16 Dated:25-Nov-2016) Corrigendum-V <a href="https://115.124.110.149/documents/d/guest/18" target="_blank">(Click here for details)</a></li>
             <li><span class="date">06.01.2017</span>: Dr.Dr.YSR AarogyasriT Bid queries and amendments -- Clarifications (Tender No.Dr.YSR Aarogyasri/PMU-IT/F4035/IT Tender/2015-16 Dated:25-Nov-2016) Corrigendum-IV <a href="https://115.124.110.149/documents/d/guest/19">(Click here for details)</a></li>
             <li><span class="date">23.12.2016</span> Revised Schedule (Tender No.Dr.YSR Aarogyasri/PMU-IT/F4035/IT Tender/2015-16 Dated:23-Dec-2016) <a href="https://115.124.110.149/documents/d/guest/20">(Click here for details)</a></li>
             <li><span class="date">13.12.2016</span>: Dr.Dr.YSR AarogyasriT Pre Bid Query Responses - Clarifications (Tender No.Dr.YSR Aarogyasri/PMU-IT/F4035/IT Tender/2015-16 Dated:25-Nov-2016) Corrigendum-II &nbsp; <a href="https://115.124.110.149/documents/d/guest/21" target="_blank" title="External file which opens in a new window">(Click here for details)</a></li>
             <li><span class="date">06.12.2016</span>: Hiring Vehicles for Officials of Dr.YSR Aarogyasri Health Care Trust period of Six months or till the Dr.Dr.YSR Aarogyasri Trust is shifted to A.P. whichever is earlier from the date of commencement of contract.&nbsp; <a href="https://115.124.110.149/documents/d/guest/22" target="_blank" title="External file which opens in a new window">(Click here for details)</a></li>
             <li><span class="date">25.11.2016</span>: Revised Schedule (Tender No.Dr.YSR Aarogyasri/PMU-IT/F4035/IT Tender/2015-16 Dated:25-Nov-2016) Corrigendum-I &nbsp; <a href="https://115.124.110.149/documents/d/guest/23" target="_blank" title="External file which opens in a new window">(Click here for details)</a></li>
             <li><span class="date">11.11.2016</span>: Notice Inviting Proposals for Selection of IT Service Provider. <a href="https://115.124.110.149/documents/d/guest/24" target="_blank" title="External file which opens in a new window">(Click here for details)</a>&nbsp; </li>
             <li><span class="date">11.08.2016</span>:Sealed quotations are invited from reputed firms for providing 140 Biometric devices which supports to operating system Windows 7, Windows 8 and Linux for easy installation of software integrated to all IT platforms(Java, .Net and Net Apps etc..) with a minimum period of 1 year carry in warranty to Dr.YSR Aarogyasri Health Care Trust. <a href="https://115.124.110.149/documents/d/guest/25" target="_blank" title="External file which opens in a new window">(Click here for Details)</a></li>
             <li><span class="date">16.06.2016</span>: Revised Bid Schedule (Tender No.Dr.YSR Aarogyasri/PMU-IT/F4035/IT Tender/2015-16 Dated:26-March-2016) Corrigendum-V&nbsp; <a href="https://115.124.110.149/documents/d/guest/26" target="_blank" title="External file which opens in a new window">(Click here for Details)</a></li>
             <li><span class="date">07.06.2016</span>: Revised Bid Schedule (Tender No.Dr.YSR Aarogyasri/PMU-IT/F4035/IT Tender/2015-16 Dated:26-March-2016) Corrigendum-IV&nbsp; <a href="https://115.124.110.149/documents/d/guest/27" target="_blank" title="External file which opens in a new window">(Click here for Details)</a></li>
             <li><span class="date">24.05.2016</span>:Revised Schedule (Tender No.Dr.YSR Aarogyasri/PMU-IT/F4035/IT Tender/2015-16 Dated:26-March-2016) Corrigendum-III&nbsp; <a href="https://115.124.110.149/documents/d/guest/28" target="_blank" title="External file which opens in a new window">(Click here for Details)</a></li>
             <li><span class="date">03.05.2016</span>:Corrigendum No.2 &amp; Pre-bid Clarifications&nbsp; <a href="https://115.124.110.149/documents/d/guest/29" target="_blank" title="External file which opens in a new window">(Click here for Details)</a></li>
             <li><span class="date">05.04.2016</span>: Revised Bid schedule for Tender Dr.YSR Aarogyasri/PMU IT/F4035/IT Tender/2015-16.&nbsp; <a href="https://115.124.110.149/documents/d/guest/30" target="_blank" title="External file which opens in a new window">(Click here for Details)</a></li>
             <li><span class="date">28.03.2016</span>: Notice Inviting Proposals for Selection of IT Service Provider&nbsp; <a href="https://115.124.110.149/documents/d/guest/31" target="_blank" title="External file which opens in a new window">(Click here for Details)</a></li>
             <li><span class="date">03.02.2016</span>: Tender document for Hiring of Vehicles for Officials of Dr.YSR Aarogyasri Health Care Trust for a period of Six(6) months&nbsp; <a href="https://115.124.110.149/documents/d/guest/32" target="_blank" title="External file which opens in a new window">(Click here for Tender document)</a></li>
    </ul>


<%@ include file="/last.jsp" %>