/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.keyPeopleService.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Designation service. Represents a row in the &quot;apgovt_designation&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.keyPeopleService.model.impl.DesignationModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.keyPeopleService.model.impl.DesignationImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Designation
 * @generated
 */
@ProviderType
public interface DesignationModel extends BaseModel<Designation> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a designation model instance should use the {@link Designation} interface instead.
	 */

	/**
	 * Returns the primary key of this designation.
	 *
	 * @return the primary key of this designation
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this designation.
	 *
	 * @param primaryKey the primary key of this designation
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the did of this designation.
	 *
	 * @return the did of this designation
	 */
	public long getDid();

	/**
	 * Sets the did of this designation.
	 *
	 * @param did the did of this designation
	 */
	public void setDid(long did);

	/**
	 * Returns the wid of this designation.
	 *
	 * @return the wid of this designation
	 */
	public long getWid();

	/**
	 * Sets the wid of this designation.
	 *
	 * @param wid the wid of this designation
	 */
	public void setWid(long wid);

	/**
	 * Returns the dname of this designation.
	 *
	 * @return the dname of this designation
	 */
	@AutoEscape
	public String getDname();

	/**
	 * Sets the dname of this designation.
	 *
	 * @param dname the dname of this designation
	 */
	public void setDname(String dname);

	/**
	 * Returns the status of this designation.
	 *
	 * @return the status of this designation
	 */
	@AutoEscape
	public String getStatus();

	/**
	 * Sets the status of this designation.
	 *
	 * @param status the status of this designation
	 */
	public void setStatus(String status);

	@Override
	public Designation cloneWithOriginalValues();

}