/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.keyPeopleService.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the KeyPeople service. Represents a row in the &quot;keyPeople&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.keyPeopleService.model.impl.KeyPeopleModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.keyPeopleService.model.impl.KeyPeopleImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see KeyPeople
 * @generated
 */
@ProviderType
public interface KeyPeopleModel extends BaseModel<KeyPeople> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a key people model instance should use the {@link KeyPeople} interface instead.
	 */

	/**
	 * Returns the primary key of this key people.
	 *
	 * @return the primary key of this key people
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this key people.
	 *
	 * @param primaryKey the primary key of this key people
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the trust_user ID of this key people.
	 *
	 * @return the trust_user ID of this key people
	 */
	public long getTrust_userId();

	/**
	 * Sets the trust_user ID of this key people.
	 *
	 * @param trust_userId the trust_user ID of this key people
	 */
	public void setTrust_userId(long trust_userId);

	/**
	 * Returns the empname of this key people.
	 *
	 * @return the empname of this key people
	 */
	@AutoEscape
	public String getEmpname();

	/**
	 * Sets the empname of this key people.
	 *
	 * @param empname the empname of this key people
	 */
	public void setEmpname(String empname);

	/**
	 * Returns the phone of this key people.
	 *
	 * @return the phone of this key people
	 */
	@AutoEscape
	public String getPhone();

	/**
	 * Sets the phone of this key people.
	 *
	 * @param phone the phone of this key people
	 */
	public void setPhone(String phone);

	/**
	 * Returns the email of this key people.
	 *
	 * @return the email of this key people
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this key people.
	 *
	 * @param email the email of this key people
	 */
	public void setEmail(String email);

	/**
	 * Returns the wing ID of this key people.
	 *
	 * @return the wing ID of this key people
	 */
	public long getWingId();

	/**
	 * Sets the wing ID of this key people.
	 *
	 * @param wingId the wing ID of this key people
	 */
	public void setWingId(long wingId);

	/**
	 * Returns the designation ID of this key people.
	 *
	 * @return the designation ID of this key people
	 */
	public long getDesignationId();

	/**
	 * Sets the designation ID of this key people.
	 *
	 * @param designationId the designation ID of this key people
	 */
	public void setDesignationId(long designationId);

	/**
	 * Returns the status of this key people.
	 *
	 * @return the status of this key people
	 */
	@AutoEscape
	public String getStatus();

	/**
	 * Sets the status of this key people.
	 *
	 * @param status the status of this key people
	 */
	public void setStatus(String status);

	/**
	 * Returns the emp order of this key people.
	 *
	 * @return the emp order of this key people
	 */
	@AutoEscape
	public String getEmpOrder();

	/**
	 * Sets the emp order of this key people.
	 *
	 * @param empOrder the emp order of this key people
	 */
	public void setEmpOrder(String empOrder);

	/**
	 * Returns the create date of this key people.
	 *
	 * @return the create date of this key people
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this key people.
	 *
	 * @param createDate the create date of this key people
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the created by of this key people.
	 *
	 * @return the created by of this key people
	 */
	@AutoEscape
	public String getCreatedBy();

	/**
	 * Sets the created by of this key people.
	 *
	 * @param createdBy the created by of this key people
	 */
	public void setCreatedBy(String createdBy);

	/**
	 * Returns the modify date of this key people.
	 *
	 * @return the modify date of this key people
	 */
	public Date getModifyDate();

	/**
	 * Sets the modify date of this key people.
	 *
	 * @param modifyDate the modify date of this key people
	 */
	public void setModifyDate(Date modifyDate);

	/**
	 * Returns the modify by of this key people.
	 *
	 * @return the modify by of this key people
	 */
	@AutoEscape
	public String getModifyBy();

	/**
	 * Sets the modify by of this key people.
	 *
	 * @param modifyBy the modify by of this key people
	 */
	public void setModifyBy(String modifyBy);

	@Override
	public KeyPeople cloneWithOriginalValues();

}