/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.keyPeopleService.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Wing service. Represents a row in the &quot;apgovt_wings&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.keyPeopleService.model.impl.WingModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.keyPeopleService.model.impl.WingImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Wing
 * @generated
 */
@ProviderType
public interface WingModel extends BaseModel<Wing> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a wing model instance should use the {@link Wing} interface instead.
	 */

	/**
	 * Returns the primary key of this wing.
	 *
	 * @return the primary key of this wing
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this wing.
	 *
	 * @param primaryKey the primary key of this wing
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the wid of this wing.
	 *
	 * @return the wid of this wing
	 */
	public long getWid();

	/**
	 * Sets the wid of this wing.
	 *
	 * @param wid the wid of this wing
	 */
	public void setWid(long wid);

	/**
	 * Returns the wname of this wing.
	 *
	 * @return the wname of this wing
	 */
	@AutoEscape
	public String getWname();

	/**
	 * Sets the wname of this wing.
	 *
	 * @param wname the wname of this wing
	 */
	public void setWname(String wname);

	/**
	 * Returns the status of this wing.
	 *
	 * @return the status of this wing
	 */
	@AutoEscape
	public String getStatus();

	/**
	 * Sets the status of this wing.
	 *
	 * @param status the status of this wing
	 */
	public void setStatus(String status);

	@Override
	public Wing cloneWithOriginalValues();

}