<%@ include file="/heading.jsp" %>
<%@ include file="/top.jsp" %>

<%@ include file="/sidebar.jsp" %>
<%@ include file="/rightContent.jsp" %>


			<h3 class="bordertitle text-dark">Claims</h3>
			<h6>Claims Processing:</h6>
			<p>All the claims processing shall be carried out electronically through the Trust portal. Payments to all the NWHs shall be made through electronic clearance facility of the Trust. The claim intimation, collection of claim documents, scrutiny of claim documents shall all be done through the Trust portal. The Trust shall follow the claim control number generated by the Trust portal for further reference. The grant of pre-authorisation by the Trust shall constitute the prima-facie evidence for any claim. Admission of a claim rests solely on three conditions viz., grant of pre-authorization for the listed therapy including changes in listed therapy necessitated by the exigencies of the case during management and intimated to the Trust within the shortest possible time, claim amount being limited to pre-auth amount, and evidence of performance of a listed therapy. An intra operative photograph or a scar photo or a case sheet is sufficient evidence for settlement of a claim. Decision of Trust on any claim settlement shall be final. As soon as the claim lands with the Trust, the following verification alone needs to be performed.</p>
			<ul> 
				<li>Verification of identity of the patient</li> 
				<li>Verification whether the claim amount is limited to pre-authorised amount.</li> 
				<li>Verification of case management as per the pre-authorisation.</li> 
				<li>Verification of evidence of treatment.</li> 
			    <li>Upon the performance of a listed therapy the NWH initiates a claim. The claim will consist of the identity of patient, pre-authorized listed therapy and pre-authorized amount with enhancement if any, and evidence of performance of listed therapy in the form of an intra-operative photograph or a scar photograph linking the identity of the patient with the therapy or case sheet.</li> 
				<li>The Trust upon receipt of the claim shall verify the identity, listed therapy, amount of the claim and evidence</li> 
				<li>Upon confirmation by means of a photograph or a medical record such as a case sheet that the listed therapy has been performed, the claim shall be settled and payment made to the NWH within 7 days.</li> 
				<li>) If the Trust is unable to establish the performance of the listed therapy in the first round of claims scrutiny, the Trust will be allowed to return the claim requesting for specific information from the NWH. Any such request or clarification by the Trust shall not result in additional investigations or diagnostic reports to be performed afresh by the NWH.</li> 
				<li>The Trust shall be allowed to send a claim back to NWH for any clarifications only once before final settlement. All remarks relating to the claim ranging from non-medical to medical queries shall be consolidated before being sent back to the NWH.</li> <li>An additional time of 7 days will be allowed in case of claim is sent back to the NWH for clarification.</li> 
				<li>The Trust issues guidelines from time to time for pre-authorisation and claims settlement which shall be followed scrupulously.</li> 
			</ul>
			<h6>Claim reduction and repudiation</h6>
			<ul> 
				<li><strong>Reduction:</strong> The settlement of a claim shall be to the full extent of the package price or pre-authorization amount whichever is lower. No disallowance can be made to a claim unless approved by the scheme technical committee of the Trust.</li> 
				<li><strong>Repudiation:</strong> The Trust may repudiate a claim for reason of not being covered by the policy under intimation to Scheme Technical Committee.</li> 
				<li>An appeal lies to the Appellate Committee either against repudiation (rejection) as defined in Term 12.4 (ii) or reduction of claim as defined in Term 12.4 (i) under Term 12.5 within 3 months from date of repudiation advice or settlement of claim.</li> 
			</ul>
			<h6>Appeal</h6>
			<ul> 
				<li>The NWH shall have a right of appeal to approach the appellate committee consisting of the Chief Medical Auditor, a member selected by the Trust from out of the panel of specialist doctors not related to the NWH and provided by the NWH, under the chairmanship of CEO. The quorum for this committee shall be three members present and voting, and majority opinion shall prevail. The decision of this appellate committee shall be final and binding on the Trust and the NWH. This right of appeal shall be mentioned by the Trust in every repudiation advice given as per Term 12.4.</li> 
				<li>The Appellate Committee shall have the power to re-open a claim if properly supported by documentary evidence.</li> 
				<li>The Appellate Committee shall have the right to reopen a settled claim and direct the Trust to settle for an appropriate amount within a period of 3 months of settlement of the claim. The Trust further agrees to provide access to the Appellate Committee their records for this purpose. All the claims settled by the Trust to the network hospitals based on the bills received from the hospitals in conformity with the package price arrived at and also based on the pre-authorization given by the Trust shall be reckoned as final and not subject to any reopening by any authority except Appellate Committee.</li> 
			</ul>
			<h6>Claim float and Bank Account</h6>
			<p>The Trust will have a separate Bank account to pay the NWH making a valid claim and all payments will be electronically cleared on the Trust portal. Detailed reports will be made available online on a real-time basis.</p>	
		

<%@ include file="/last.jsp" %>